// All intervals below refer to the owner's ORIGINAL recording clock, in seconds.
import { ACTIVE_FLOWS } from './casestudy2-active-data.js';
// Source video timing is retained. Scene ranges are editorial cuts, not animation durations.
export const LAYERS={image:{label:'Görsel / kamera',color:'#7993aa'},mask:{label:'Maske / zemin',color:'#a07759'},text:{label:'Yazı / içerik',color:'#8b9468'},ui:{label:'Arayüz',color:'#928197'}};
const track=(type,note,range=[0,1],box=null)=>({type,note,range,box});
const I=(note,range,box)=>track('image',note,range,box),M=(note,range,box)=>track('mask',note,range,box),T=(note,range,box)=>track('text',note,range,box),U=(note,range,box)=>track('ui',note,range,box);
// Annotation rectangles are reading regions, expressed as percent of the recorded viewport.
// They do not pretend to be extracted DOM objects or pixel-perfect compositing masks.
const c=(key,start,end,title,family,summary,layers,lesson,phases=[])=>({key,sourceStart:start,sourceEnd:end,title,family,summary,layers,lesson,phases:phases.length?phases:[[0,'Başlangıç',layers[0]?.note||summary],[.5,'Hareket',layers[1]?.note||summary],[.94,'Varış',layers[2]?.note||summary]]});

const eraDesktop=[
 c('identity',3,10.4,'Kimlik ve yükleme izi','Açılış','Bordo zemin üzerinde marka, kıyı isimleri ve ince yükleme izi birlikte okunur. Sonraki görüntü henüz açılmaz.',[M('Bordo örtü bütün kadrajı kaplar.',[0,1],[0,0,100,100]),T('Marka merkezde; kıyı isimleri iki yana dağıtılır.',[.1,1],[22,30,56,40]),U('İnce yükleme izi merkezin altındadır.',[.25,1],[48,63,4,25])],'Açılışın ilk görevi kimlik ve bekleme ritmi kurmak; henüz kamera yolculuğu başlamamalı.'),
 c('arch-intro',10.4,13.4,'Kemer açılır, sahne genişler','Maske','Mimari görüntü önce dar bir kemerin içinde görünür. Açıklık genişlerken bordo örtü gider ve hero bütün ekranı devralır.',[I('Aynı mimari kadraj açıklığın arkasında kalır.',[0,1],[0,0,100,100]),M('Kemerin yükselmesi ve genişlemesi birlikte çalışır.',[0,.9],[31,8,38,92]),T('Hero kimliği örtünün ardından görünür.',[.4,1],[34,0,33,50])],'Daralmayı veya büyümeyi resme tek başına uygulama; örtü, açıklık ve arka kadrajı aynı girişin parçaları olarak düşün.',[[0,'Dar açıklık','Binanın küçük bir bölümü kemerin içinden görünür.'],[.38,'Genişleyen eşik','Kemer büyür; bordo yüzeyin kapladığı alan azalır.'],[.93,'Tam ekran','Örtü gider, kaynak görüntü ve kimlik hero ölçeğine oturur.']]),
 c('cookie',13.4,24.2,'Hero ve cookie kartı','Arayüz','Hero açıkken sağ alt köşedeki cookie kartı ayrı bir ön katman olarak durur. Kayıtta kullanıcı kartı kapatır.',[I('Hero fotoğrafı kadrajı doldurur.',[0,1]),T('Büyük serif marka ve script yer adı görselin üzerine yerleşir.',[0,1],[30,0,39,50]),U('Cookie kartı sağ altta; kapanınca arka görüntü kesilmez.',[0,.92],[77,55,21,42])],'Küçük yardımcı katmanlar ana görselin girişini yeniden başlatmamalı.'),
 c('pins',24.2,32.6,'Pin → imleçte bilgi kartı','Etkileşim','Üç farklı mimari nokta dolaşılır. Küçük pin vurgusu ve beyaz bilgi kartı, aynı arka görüntü üzerinde değişir.',[I('Havuz ve bina aynı kadrajda kalır.',[0,1]),U('Pin halkaları ve imleç konumu etkileşim odağıdır.',[0,1],[30,43,60,48]),T('CRAFTED TO ENDURE, LIGHT & FLOW ve YOUR PRIVATE SANCTUARY kartları farklı noktalarda açılır.',[.08,.98],[21,38,76,62])],'Her kamera noktası için ayrı görsel bağlam ve doğru bilgi gerekir; bütün noktaları tek sabit karta bağlama.',[[0,'Birinci nokta','Mimari noktaya gelinir, bilgi kartı görünür.'],[.42,'Kart yer değiştirir','İkinci noktanın başlığı ve konumu birlikte değişir.'],[.85,'Yeni odağı okuma','Havuz yanındaki üçüncü nokta kendi açıklamasını getirir.']]),
 c('hero-dive',32.6,36,'Havuza kamera yaklaşması','Kamera','Kaydırma hero başlığını kadraj dışına taşırken görüntü havuz yönünde yaklaşır. Alt taraftaki masa ve su daha belirgin hale gelir.',[I('Yaklaşmanın hedefi görüntünün alt merkezidir.',[0,1],[10,35,85,65]),T('Hero yazısı görüntüden farklı hızla yukarı çıkar.',[0,.7],[25,0,50,30]),U('Sabit monogram ve sağ navigasyon tema içinde kalır.',[0,1])],'Kamera hareketi bir hedefe yaklaşmalı. Görselin mimari odağını sabit tutan ölçek merkezi seç.'),
 c('arch-cover',36,38.5,'Büyük kavis sahneyi devralır','Maske','Buz mavisi bölümün geniş kavisli tepesi havuz görüntüsünün üstüne yükselir. Kavis üzerindeki yazı ve yeni bölüm aynı hareketten doğar.',[I('Yakınlaşmış hero görüntüsü örtünün arkasında kalır.',[0,.6]),M('Buz mavisi kavis aşağıdan büyüyerek kadrajı kaplar.',[0,1],[0,18,100,82]),T('THREE REASONS TO CHOOSE ERA yazısı kavis boyunca taşınır.',[.08,.8],[15,12,70,34])],'Bir sonraki bölümün biçimini önceki görüntünün üstünde görünür kıl; görüntüyü bir anda başka renge kesme.'),
 c('reasons',38.5,42.2,'Üç neden: başlık, görsel, sayaç','Tipografi','REAL-LIFE LOCATION başlığı, küçük orta görsel ve açıklama buz mavisi sahnede açılır. Desktop kaydında bu slaydın girişini görüyoruz.',[T('Başlık ve paragraf aynı anda tam görünür olmaz.',[0,.75],[15,0,70,92]),I('Küçük görsel merkezde ayrı bir pencere olarak açılır.',[.12,1],[40,32,20,38]),U('Görselin altında sayaç ve kontrol çizgisi bulunur.',[.3,1],[37,66,26,9])],'Görsel küçükse çevresindeki boşluk, yazının ölçeği ve sayaç bir bütün olmalı.'),
 c('alpha-quote',42.2,45.8,'Mimari siluet → konsept','Paralaks','Bina ve havuz görüntüsünün silueti buz mavisi zeminden taşar. Görüntü yukarı giderken kırık beyaz konsept zemini ve çiçekler görünür.',[I('Mimari görünüm zeminle birlikte hareket etmeyen ayrı bir görsel katmandır.',[0,1],[0,0,100,100]),M('Buz mavisi ve kırık beyaz sahneler üst üste gelir.',[.25,1]),T('Mimari alıntı binanın üzerine yerleşir.',[0,.65],[57,0,37,34])],'Keskin dikdörtgen sınır yerine siluet kullanılması, ancak doğru alpha materyalle anlamlıdır.'),
 c('concept',45.8,49.2,'Konsept ve ön plan çiçekleri','Kompozisyon','Konsept metni ortada okunurken üst sol ve alt sağ çiçekler görüntüye derinlik verir. Sonunda yatay konum sahnesi sağdan görünmeye başlar.',[I('Çiçekler iki ayrı ön plan konumunda hareket eder.',[0,1],[0,0,100,100]),T('Ana konsept cümlesi merkezde; küçük açıklama altında.',[0,.8],[20,25,60,57]),M('Bir sonraki sahne sağ kenardan kadraja girer.',[.7,1],[80,0,20,100])],'Dekor, metnin alanını işgal etmeden bölüm değişiminin yönünü hissettirmeli.'),
 c('horizontal',49.2,55.6,'Düşey scroll, yatay konum akışı','Yatay','NEW GOLDEN MILE başlığı ve teras görseli sola taşınır. Aynı ray üzerinde sahil başlığı ve rota şeması sağdan gelir.',[I('Teras fotoğrafı rayın parçası olarak sola gider.',[0,.65],[23,0,39,100]),T('Üç satırlı başlık görsele göre farklı yatay konumlarda okunur.',[0,1],[0,4,45,87]),M('Kırık beyaz zemin süreklidir; sert bölüm kesmesi yoktur.',[0,1])],'Yatay sahneler için gerçek genişliği ve sonraki hedefi planla; birkaç bağımsız kartı yana itmek aynı kurgu değildir.'),
 c('route',55.6,58.2,'Rota çizgisi ve bulut eşiği','Katman','Sahil cümlesi ve kıvrımlı rota çizgisi yatay rayın sonunda yerleşir. Alttaki bulut katmanı yeni geniş konum görüntüsünü haber verir.',[I('Bulutlar alttan görünerek aerial sahneye bağlanır.',[.3,1],[0,65,100,35]),T('Rota üzerindeki yer adları çizgiye bağlı kalır.',[0,1],[12,30,77,29]),M('Rota, boş kırık beyaz alan içinde bir çizgiyle okunur.',[0,1])],'Rota grafiği kendi açıklamasını taşımalı; dekoratif bir eğri kadar bırakılmamalı.'),
 c('aerial',58.2,62.2,'Bulutlardan geniş aerial’a','Paralaks','Geniş çevre görüntüsü ve dağ silueti bulutların altında açılır. Kamera kadrajı geniş konumu okuturken konut tipleri alttan yaklaşır.',[I('Aerial görüntü ana arka plandır.',[0,1],[0,0,100,100]),M('Bulutlar aerial üstünde yarı saydam bir geçiş oluşturur.',[0,.65],[0,0,100,40]),T('Yeni bölüm yazısı aerial’ın altından görünür.',[.75,1])],'Sahne içindeki atmosfer ile esas mekân görüntüsünü farklı hareket katmanlarında tut.'),
 c('residence-type',62.2,68.4,'Konut tipi: görsel ve ölçü','Tipografi','Ground floor + basement görseli, başlık ve alan bilgisi birlikte yerleşir. Ardından genel konut açıklaması aşağıda belirir.',[I('Küçük dikey konut görseli merkezde kalır.',[0,.58],[42,8,18,54]),T('Konut başlığı ve ölçüler görseli açıklayan aynı gruptadır.',[0,1],[28,8,50,90]),U('Slayt okları, CTA ve sayaç küçük alt sıradadır.',[.05,.55])],'Görseli kat adı ve ölçüyle eşleştir; hiçbirini bağımsız animasyon süsü yapma.'),
 c('amenity-tabs',68.4,82.2,'Amenity: yönlü görsel değişimi','Etkileşim','Gated community, swimming pool, parking ve spa görüntüleri sırayla değişir. Seçili liste satırı ve alttaki açıklama görüntüyle birlikte güncellenir.',[I('Görseller eğimli bir kenardan birbiri üzerine geçer.',[0,1],[0,0,100,100]),M('Geçiş sınırı yeni görseli açarken eskisini örter.',[.12,.95],[0,0,100,100]),T('Her seçimin kendi başlığı ve açıklaması vardır.',[0,1],[0,62,75,36]),U('Sağdaki liste yeni seçimi işaretler.',[0,1],[69,17,25,29])],'Görsel, seçili satır ve açıklamayı aynı durumdan yönet; önceki katın yazısını yeni görsel üzerinde bırakma.',[[0,'Gated community','Bütün sahne ve sağdaki seçili satır okunur.'],[.34,'Pool → parking','Görsel maskesi ve yeni açıklama aynı yönlü geçişte değişir.'],[.88,'Spa','Sıcak iç mekân görseli son seçim olarak yerleşir.']]),
 c('interior-arch',82.2,84.7,'İkinci kavis: iç mekâna giriş','Maske','Kırık beyaz geniş kavis spa fotoğrafının üstüne yükselir. THE SPACE TO ve script Live in yazısı kavisli zemine yerleşir.',[I('Spa fotoğrafı önceki sahne olarak arkada kalır.',[0,.7]),M('Kırık beyaz kavis bütün kadrajı devralır.',[0,1],[0,15,100,85]),T('Serif ve script başlık farklı ritimde açılır.',[.15,1],[30,24,40,66])],'Tekrarlanan maske, yeni sahnenin tipografisini ve rengini taşıdığı için yeni bir anlatı eşiği olur.'),
 c('interior-columns',84.7,88.5,'Zıt kolonlar ve ön plan bitkisi','Paralaks','Sol tarafta bordo kart ve çiçekli görsel, sağ tarafta teras ve açıklama farklı düşey hizalarda ilerler.',[I('Sol ve sağ fotoğraflar zıt hizada taşınır.',[0,1],[0,0,100,100]),M('Bordo kart sadece sol kompozisyonun zemini olur.',[0,1],[0,28,40,72]),T('Sağ açıklama kendi fotoğrafının altında kalır.',[0,1],[45,45,52,39])],'Fotoğraf ve caption aynı blokta kalsın; iki kolonun hız farkı okumayı bölmemeli.'),
 c('interior-gallery',88.5,90.4,'İç galeri → mimari eşik','Galeri','Yatak odası görseli ve küçük slayt kontrolleri yukarı ilerler. Altta iki farklı yükseklikteki mimari pencere görünmeye başlar.',[I('Galeri fotoğrafı üstte; yeni mimari pencereler altta.',[0,1]),U('Galeri okları ve sayaç resim altında kalır.',[0,.65]),M('Yeni sahnenin iki pencere açıklığı boş zeminde belirir.',[.3,1])],'Bir sonraki hareketin ilk durumunu önceki sahnenin çıkışında göster.'),
 c('architecture-merge',90.4,94.2,'İki pencere hizalanır ve birleşir','Birleşme','Başta farklı seviyelerde olan iki mimari açıklık ortak banda gelir, orta sınır erir ve birleşik kadraj büyümeye başlar.',[I('İki açıklıkta aynı mimari sahnenin devamı görülür.',[0,1],[18,13,64,75]),M('Hizalanma → orta boşluğun kapanması → genişleme ayrı aşamalardır.',[0,1],[18,13,64,75]),I('Ön plandaki çiçekler birleşmenin iki yanında kalır.',[0,.9])],'Birleşme üç adım ister: hizala, sınırı kaldır, yeni sahneye yaklaş. İki fotoğrafı aynı anda büyütmek yeterli değildir.',[[0,'Farklı seviyeler','Sol açıklık daha aşağıda, sağ açıklık daha yukarıdadır.'],[.45,'Ortak bant','Üst ve alt kenarlar aynı görüş çizgisine gelir.'],[.82,'Bir açıklık','Orta sınır kaybolur; bütün kompozisyon büyümeye başlar.']]),
 c('architecture-dive',94.2,97.7,'Birleşik kadrajın içine dalış','Kamera','Mimari pencere ekranı devralır; ARCHITECTURE yazısı üstten gelir. Kamera düşey hareketini sürdürürken alıntı ve CTA açılır.',[I('Mimari fotoğraf tam ekrana büyür ve aşağıdaki cepheyi gösterir.',[0,1]),M('Ön açıklığın kenarları kadraj dışına çıkar.',[0,.5]),T('Büyük başlık ardından daha küçük mimari açıklama görünür.',[0,1],[7,0,86,85])],'Giriş hareketi tamamlandıktan sonra sahne içindeki kamera akışı devam edebilir; iki hareketi farklı eşikler olarak yönet.'),
 c('architecture-exit',97.7,104.8,'Fotoğraf geri çekilir, bilgi açılır','Kadraj','Mimari fotoğrafın altında beyaz bilgi sahnesi görünür. Developer, sales, license ve yıl başlıkları bir sonraki düzleme yerleşir.',[I('Mimari görsel üstte kalan bir bant halinde uzaklaşır.',[0,.8]),M('Kırık beyaz zemin alttan sahneyi devralır.',[0,1]),T('Küçük giriş etiketi ardından bilgi başlıkları açılır.',[.2,1],[24,43,54,53])],'Küçülen görüntünün açtığı alan yeni bilgiyle dolmalı. Boş bir kutu küçülmesi olarak bırakma.'),
 c('closing-cta',104.8,108.2,'Teras ve büyük kapanış başlığı','Paralaks','Geniş teras fotoğrafı alttan gelir; PERFECT SEA VIEWS ve script vurgu sahnenin üzerine açılır.',[I('Teras resmi yeni tam ekran sahnedir.',[0,1]),T('Büyük başlık önce, küçük CTA daha sonra okunur.',[.18,1],[17,2,65,64]),U('Dairesel apartman CTA’sı görüntü üstündedir.',[.55,1],[40,52,22,37])],'Son bölümde fotoğrafın konusu ile satın alma/viewing çağrısı birbiriyle uyumlu olmalı.'),
 c('footer',108.2,112.8,'Footer: daralan görüntü, büyüyen içerik','Maske','Teras görüntüsünün görünür alanı daralırken bordo footer ve telefon bilgisi belirir. Görüntü tek başına boş bir kutu haline gelmez.',[I('Teras resmi orta üstte kalan pencereye dönüşür.',[0,1],[24,0,52,51]),M('Bordo footer, daralan resmin etrafında görünür olur.',[0,1]),T('Monogram, telefon ve alt bilgiler yeni zeminde açılır.',[.2,1],[23,44,54,54])],'Footer önce kendi hiyerarşisiyle kurulmalı; resim onun içindeki bilinçli boşluğa yerleşmeli.',[[0,'Tam teras','Önceki fotoğraf kadrajın çoğunu kaplar.'],[.42,'Çerçeve açılır','Görünür alan daralırken bordo zemin büyür.'],[.88,'Footer okunur','Telefon ve iletişim bilgileri yeni sahnenin ana içeriğine dönüşür.']]),
 c('footer-reverse',112.8,116.1,'Aynı geçişin geri okunması','Ters akış','Kullanıcı yukarı kaydırır. Footer içeriği geri çıkar ve teras görüntüsü yeniden kadrajı doldurur.',[I('Aynı resim tekrar büyür.',[0,1]),M('Bordo alan daralarak geriye çekilir.',[0,1]),T('Footer bilgisi çıkar, büyük CTA başlığı geri gelir.',[0,1])],'Ters scroll yeni bir efekt değildir; aynı düzenin doğru geri oynatılmasıdır.'),
 c('page-change',116.1,120.5,'Ana sayfa → apartments','Sayfa geçişi','CTA seçildikten sonra mevcut teras sahnesi gider; kırık beyaz apartman listesi, büyük başlık ve plan kartları açılır.',[I('Eski teras görünümü yeni sayfaya taşınmaz.',[0,.3]),M('Sayfa örtüsü ve beyaz boşluk geçişe ara durum verir.',[.18,.65]),T('APARTMENTS, 25 ve plan kartları yeni hiyerarşiyi kurar.',[.4,1])],'Başka sayfaya geçerken eski sahne durumunu temizle ve yeni sayfanın ilk kadrajını tamamıyla kur.'),
 c('plan-detail',120.5,124.1,'Plan kartı → daire detayı','Plan','Liste planı seçilir; NO.011 detayındaki büyük plan ve yanındaki oda/alan bilgisi yeni bir düzen kurar.',[I('Plan çizimi hem kartta hem detay kadrajında okunur.',[0,1],[15,15,55,72]),T('Daire kimliği ve ölçü bilgisi sağdaki sabit sütundadır.',[.25,1],[67,13,28,76]),U('Listeye dön ve inquiry kontrolleri planın altında yer alır.',[.45,1])],'Plan görseli gerçek bilgi merkezidir; oda adları, alan ve seçimin sonucu aynı yerde anlaşılmalı.'),
 c('detail-gallery',124.1,130.4,'Fotoğraf sütunu ve sabit bilgiler','Galeri','Banyo ve yaşam alanı fotoğrafları sol sütunda akarken NO.011 ve metrekare bilgisi sağda görünür kalır.',[I('Birbirini izleyen fotoğraflar sol geniş sütunda ilerler.',[0,1],[6,0,66,100]),T('Oda ve alan bilgisi sağ sütunda sabit bağlam sağlar.',[0,1],[72,0,28,96]),U('Büyütme noktaları fotoğrafın üstünde yer alır.',[0,1])],'Fotoğraf değişirken hangi mülkü veya katı gördüğümüz kaybolmamalı.'),
 c('lightbox',130.4,135.3,'Lightbox açılır, yana geçer, kapanır','Etkileşim','Bir fotoğraf büyütülür. Kırık beyaz tam ekran katmanda görseller sağa/sola değişir, kapanınca detay sütununa geri dönülür.',[I('Büyütülen fotoğraf ayrı tam ekran okumaya geçer.',[.12,.9],[27,8,46,86]),M('Açık renk overlay detay sayfasını örter.',[0,.92]),U('Kapatma ve ileri/geri düğmeleri büyük fotoğraftan ayrıdır.',[.15,.95])],'Büyütme ayrı bir mod olmalı; kapanınca önceki scroll ve seçili fotoğraf bağlamına dön.'),
 c('similar',135.3,143.8,'Benzer seçenekler ve tekrar kavis','Kurgu','Detay galerisi biter, geniş hero benzeri görünüm gelir; ardından SIMILAR OPTIONS kavisinin altında yeni plan kartları açılır.',[I('Konut fotoğrafı kartlara geçiş için ara sahne olur.',[0,1]),M('Büyük beyaz kavis plan listesini taşır.',[.22,.78]),T('SIMILAR OPTIONS ardından planların açıklamaları görünür.',[.25,1])],'Tekrarlanan geometri, ana sayfadan detay sayfasına aynı anlatı dilini taşıyabilir.'),
 c('return-list',143.8,151,'Listeye dönüş ve yeniden giriş','Sayfa geçişi','Teras sahnesinden apartments listesine dönülür. Beyaz ara durumun ardından başlık ve plan kartları yeniden açılır.',[M('Kırık beyaz ara yüzey sayfayı değiştirir.',[0,.55]),T('APARTMENTS başlığı ve 25 sayısı tekrar yerleşir.',[.3,1]),I('Plan kartları yeni sayfanın başlangıç durumunu tamamlar.',[.5,1])],'Sayfaya yeniden giriş, kaldığı yerde yarım çalışan eski bir timeline ile başlamamalı.')
];

const eraMobile=[
 c('hero-dive',160,164,'Mobil hero ve yaklaşma','Kamera','Dikey kadrajda büyük kimlik, havuz ve mobil CTA birlikte görünür. Kayıt doğrudan açık hero durumuyla başlar; mobil yükleme animasyonu bu bölümde yoktur.',[I('Mimari fotoğraf dikey ekrana göre yeniden kadrajlanmıştır.',[0,1]),T('Marka ve script yer adı dikey hiyerarşide üst üste gelir.',[0,1],[11,22,80,50]),U('Mobil CTA havuz üstünde; Menü sağ üsttedir.',[0,1])],'Mobil versiyon masaüstünü küçültmek değildir; metin ve mimari odağı dikey kadraj için yeniden yerleştir.'),
 c('arch-cover',164,167,'Mobil kavis ekranı kaplar','Maske','Buz mavisi kavis alttan yükselip hero’yu örter. Kavis yazısı dar ekranın genişliğine oturur, sonraki başlık açılır.',[I('Hero aynı kadrajda arkada kalır.',[0,.6]),M('Kavis dar ekranda bütün genişliğe yayılır.',[0,1]),T('Kavis yazısı çıkar; REAL-LIFE LOCATION başlığı gelir.',[.1,1])],'Maske oranını ekran genişliğiyle birlikte çöz; başlık alanını bırakacak tepe yüksekliği seç.'),
 c('reasons',167,170,'Üç neden: mobil yerleşim','Tipografi','Başlık, büyükçe yatay görsel ve paragraf dikey sırada okunur. Mimari siluet sayfanın altında görünür kalır.',[T('Başlık fotoğrafın üzerinde, açıklama altında yerleşir.',[0,1],[5,0,90,79]),I('Neden görseli mobil genişliğini kullanır.',[0,1],[5,26,90,32]),U('Slayt kontrolü fotoğrafın altında kısa bir satırdır.',[0,1])],'Mobilde küçük desktop görselini küçültmeye devam etme; açıklamanın okunmasına göre fotoğrafı büyüt.'),
 c('reasons-carousel',170,177,'Nedenler: üç gerçek slayt','Galeri','Teras, mimari ve bahçe görselleri ile açıklamaları değiştirilir. Sayaç 2, 3 ve 1 durumlarını gösterir.',[I('Yeni görsel bir önceki fotoğrafın yerini alır.',[0,1],[0,0,100,37]),M('Eğimli sınır fotoğraflar arasındaki geçişi taşır.',[.15,.95],[0,0,100,37]),T('Her slaytta açıklama da değişir.',[0,1],[4,34,92,29]),U('Oklar ve sayaç kullanıcıya geçiş yönünü verir.',[0,1],[7,23,86,11])],'Görselin değişimini yeni açıklama ve sayaçla tamamla; eski metni resim değişirken bekletme.'),
 c('alpha-quote',177,178.7,'Mimari siluet ve çiçek eşiği','Paralaks','Bina silueti üstten uzaklaşır; pembe ön plan çiçeği ve kırık beyaz konsept zemini alttan girer.',[I('Mimari kesit ve çiçek ayrı hız katmanlarıdır.',[0,1]),M('Mavi zeminden beyaz zemine geçiş siluet sınırında gerçekleşir.',[0,1]),T('Konsept cümlesi alttan görünmeye başlar.',[.55,1])],'Fotoğrafın kenarı yeni bölümün başlangıcı olabilir; maske dikişini sahnenin anlamıyla eşleştir.'),
 c('concept',178.7,180.4,'Konsept tek kolonda açılır','Tipografi','Konsept cümlesi ve küçük paragraf dikey yerleşir; çiçek solda ve üstte okuma alanını çerçeveler.',[I('Çiçek metnin önünde ayrı dekor katmanıdır.',[0,1]),T('Uzun konsept başlığı mobil satırlara yeniden kırılır.',[0,1],[6,6,88,80]),M('Kırık beyaz zemin konseptten konuma devam eder.',[0,1])],'Uzun cümlede doğal mobil satır kırılımlarını koru; desktop karakter konumlarını telefona kopyalama.'),
 c('horizontal',180.4,185.4,'Konum hikâyesi düşey okunur','Mobil uyarlama','NEW GOLDEN MILE, teras, açıklama, dairesel CTA ve sahil cümlesi art arda aşağı iner. Desktop’taki bütün yatay ray küçültülmez.',[I('Teras resmi metinler arasında tam genişlikte okunur.',[0,.6]),T('Desktop yatay sahnenin yazıları burada düşey sıraya geçer.',[0,1]),U('Dairesel CTA geniş metin aralığında ayrı durur.',[.35,.75])],'Mobil karşılığı bir ölçek değişimi değil, sahne sırasının yeniden düzenlenmesidir.'),
 c('route',185.4,189,'Mobil rota ve yatay kadraj','Katman','Sahil başlığı, kıvrımlı rota ve bulut eşiği görünür. Rota üzerindeki yer adları yatay kadraj hareketiyle değişir.',[I('Bulutlu aerial altta yeni zemin olarak görünür.',[.2,1]),T('Rota adları aynı çizgi üzerinde bağlı kalır.',[0,.9],[0,22,100,40]),M('Dar kadraj rota çizgisinin tamamını bir seferde göstermez.',[0,1])],'Mobilde uzun grafiğin nasıl okunacağını ayrıca tanımla; kadraj içi sürükleme ile ana sayfa scroll’unu ayır.'),
 c('aerial',189,191,'Aerial → konutlar','Paralaks','Bulutlu geniş çevre resmi kadrajı doldurur. Mavi konut bölümü aşağıdan gelirken aerial üstte kalarak çıkar.',[I('Çevre görüntüsü farklı mobil kadrajda görünür.',[0,1]),M('Konutların mavi zemini alttan üstüne gelir.',[.4,1]),U('DRAG TO SEE MORE işareti aerial üzerinde kalır.',[0,.7])],'Dikey resimde önemli bina/çevre ilişkisi korunmalı; yatay görüntüyü anlamsız bir dar crop’a dönüştürme.'),
 c('residence-type',191,197,'Konut tipi ve ölçüler','Plan bilgisi','Fotoğraf, Ground floor + basement başlığı, oda sayısı ve alan bilgisi tek kolonda görünür; sonra genel konut metni gelir.',[I('Konut görseli önce büyük bir dikey pencere olarak okunur.',[0,.6],[9,9,82,61]),T('Başlık, metrekare ve açıklama aynı dikey akışı izler.',[0,1]),U('CTA ve slayt kontrolü alan bilgisine yakın kalır.',[.35,.65])],'Kat bilgisi küçük etikete sıkışmamalı. Önce görseli, ardından ölçü ve gündelik kullanımını okut.'),
 c('amenity-tabs',197,205.6,'Amenity: aynı seçim, dikey kadraj','Etkileşim','Gated community, swimming pool, parking ve spa seçilir. Dikey görüntüde başlık listesi üstte, açıklama altta kalır.',[I('Görseller aynı mobil çerçevede değişir.',[0,1]),M('Eğik wipe yeni fotoğrafı açar.',[0,1]),T('Açıklama her seçimin kendi içeriğine geçer.',[0,1],[3,71,94,26]),U('Seçili liste satırı üstte kalır.',[0,1],[20,16,74,27])],'Dar ekranda seçenekler görseli gereksiz örtmemeli; seçili satırla açıklama arasındaki bağ korunmalı.'),
 c('interior-arch',205.6,207.5,'İç mekânın kavisli girişi','Maske','Beyaz kavis spa fotoğrafının üzerine yükselir. Büyük serif başlık ve script vurgu yeni bölümün kimliğini getirir.',[I('Spa arkada çıkar.',[0,.6]),M('Büyük beyaz kavis sahneyi kaplar.',[0,1]),T('THE SPACE TO ve Live in başlığı dikey sırada açılır.',[.15,1])],'Aynı geçiş ailesinin mobil oranlarını ayrıca kur; maskeyi kesen video zoom/fitleme olmamalı.'),
 c('interior-columns',207.5,212.7,'İç mekân: kolonlar tek akışa dönüşür','Mobil uyarlama','Bordo kart, bahçe resmi, teras resmi, açıklamalar ve yatak odası galeri görseli aşağıda art arda görünür.',[I('Desktop iki kolonunun görselleri tek dikey hikâyeye dönüşür.',[0,1]),M('Bordo resim kartı beyaz zemin üzerinde ayrı yüzeydir.',[0,.4]),T('Caption ve açıklamalar kendi fotoğrafından ayrılmaz.',[0,1])],'Desktop zıt kolonlarını telefonda yan yana sıkıştırma; hikâyeyi doğru görsel sırasıyla yeniden anlat.'),
 c('architecture-mobile',212.7,214.9,'Mimari: doğrudan bölüm girişi','Mobil uyarlama','Mobilde desktop’taki iki pencere birleşmesi yerine geniş mavi gökyüzü ve ARCHITECTURE başlıklı doğrudan fotoğraf girişi görülür.',[I('Mimari cephe tek fotoğraf olarak sahneye gelir.',[0,1]),M('Önceki galeri ile yeni görüntü düşey komşudur.',[0,1]),T('ARCHITECTURE başlığı büyük gökyüzü alanında açılır.',[.15,1],[2,10,96,19])],'Mobilde olmayan bir desktop birleşmesini varmış gibi yeniden üretme; gerçek karşılık doğrudan görsel girişidir.'),
 c('interior-gallery',214.9,220.5,'İç galerinin mobil kontrolü','Galeri','Kullanıcı geri kaydırır, yatak odası, yaşam alanı ve bitkili avlu fotoğraflarını aynı galeri penceresinde değiştirir.',[I('Üç farklı mekân fotoğrafı seçilir.',[0,1],[0,13,100,66]),M('Yeni fotoğrafın giriş sınırı aynı galeri alanında kalır.',[.2,.95]),U('Ok ve sayaç fotoğraf altında görünür.',[0,1],[5,77,90,13])],'Galeri seçimi ana sayfanın akışından bağımsız kalmalı; galeriyle scroll birbirini kilitlememeli.'),
 c('architecture-dive',220.5,223.5,'Mimari cephe ve alıntı','Paralaks','Cephe kadrajı aşağı iner; büyük başlık çıkar ve mimari alıntı/ekip bilgisi görüntü üzerinde görünür hale gelir.',[I('Fotoğraf cepheyi aşağı yönlü gösterir.',[0,1]),T('Başlık yerine mimari alıntı ve ekip kredisi görünür.',[0,1],[3,67,94,30]),U('Üstteki mobil menü kendi renk karşılığını korur.',[0,1])],'Fotoğraf içi hareketi metnin okunacağı açık alanla birlikte tasarla.'),
 c('architecture-exit',223.5,225.3,'Mimari → proje bilgisi','Kadraj','Mimari fotoğraf üstten ayrılır; beyaz zeminde developer, sales, license ve yıl başlıkları görünür.',[I('Fotoğraf üstte kalan bant olarak çıkar.',[0,.5]),M('Beyaz bilgi zemini ön sahneye geçer.',[0,1]),T('Dört bilgi satırı dikey sırada açılır.',[.2,1],[4,22,87,75])],'Bilginin satır aralarını mobilde koru; sahne değişimi bütün metni tek anda kadraja yığmamalı.'),
 c('closing-cta',225.3,227.2,'Teras ve mobil kapanış','Paralaks','Teras fotoğrafı, büyük kapanış başlığı ve mobil CTA aynı dikey görüntüde görünür.',[I('Dikey teras kadrajı ana zemin olur.',[0,1]),T('PERFECT SEA VIEWS ve script alt satır fotoğrafın üzerine açılır.',[0,1],[0,0,100,65]),U('VIEW AVAILABLE APARTMENTS bağlantısı orta alanda yerleşir.',[.3,1])],'CTA için fotoğrafın en önemli mekânını kesmeyen bir yazı alanı ayır.'),
 c('footer',227.2,234.7,'Mobil footer: ince pencereye dönüşme','Maske','Teras görüntüsü dar bir üst pencereye çekilir. Bordo zemin, telefon ve alt bilgiler onun etrafında açılır; kullanıcı ileri–geri hareketi de gösterir.',[I('Teras görünür alanı mobilde çok daha dar bir pencereye dönüşür.',[0,1],[31,0,38,28]),M('Bordo alan görüntü etrafında büyür.',[0,1]),T('Telefon ve adres yeni sahnenin ana içeriğidir.',[.2,1],[0,38,100,61])],'Footer kadrajı desktop’tan farklı oran ister; resimle yeni içeriği aynı ilerlemeyle bağla.'),
 c('footer-reverse',234.7,238,'Footer → teras geri dönüşü','Ters akış','Telefon ve bordo zemin geri çekilir; teras fotoğrafı yeniden büyür, PERFECT SEA VIEWS başlığı geri gelir.',[I('Aynı görüntü yeni tam ekran görünümüne geri açılır.',[0,1]),M('Bordo örtü kadrajdan çıkar.',[0,.8]),T('Büyük kapanış başlığı yeniden okunur.',[.2,1])],'İleri yön kadar geri yönün varış kadrajı da tam olmalı; yeni bir fit veya zoom atlaması yapılmamalı.')
];

const likovaDesktop=[
 c('identity',113.5,117.4,'Model, logo kartı ve yükleme','Açılış','Koyu zemin üzerindeki binanın çevresinde beyaz LIKOVA kartı görünür. Yüzde ilerler, model gider ve logo kartı sonraki zemine bağlanır.',[I('Üç boyutlu bina kimliğin arkasında dönük bir açıyla durur.',[0,.8]),M('Beyaz basamaklı kart ayrı bir ön katmandır.',[0,1],[32,28,36,43]),T('LIKOVA ve yüzde kartın içinde kalır.',[0,1])],'Yükleme görseli, açılacak binanın kimliğiyle bağlantılı olabilir; ilerleme ve model aynı hiyerarşide okunmalı.'),
 c('hero',117.4,121.1,'Basamaklı yüzey hero’yu açar','Maske','Beyaz logo yüzeyi üstte kalırken bina görüntüsü alttan görünür. Kartın kademeli kenarı görüntünün giriş biçimini belirler.',[I('Ana bina render’ı alttan kadraja açılır.',[0,1]),M('Beyaz basamaklı yüzey kadrajın üstünde geriye çekilir.',[0,1]),T('Logo ve küçük hero cümlesi yeni kadrajda açılır.',[.25,1])],'Maske kenarı markanın görsel diline ait olmalı; rastgele bir geometrik wipe kullanma.'),
 c('menu',121.1,125,'Sol menü paneli','Etkileşim','Beyaz menü soldan açılır, sağdaki hero kararır. Bölüm listesi, bina çizimi ve CTA’lar menü içinde görünür; kapanınca hero’ya dönülür.',[I('Ana hero sağda konumunu korur.',[0,1]),M('Solda beyaz panel, sağda kararan overlay aynı anda açılır.',[0,1],[0,0,46,100]),T('Bölüm listesi ve plan çizimi menü paneli içindedir.',[.15,.9]),U('Kapatma ve CTA’lar menüye ait ayrı kontrollerdir.',[0,1])],'Menü açılırken arka sahnenin konumu korunmalı; kapanınca aynı kadraja dön.'),
 c('hero-scroll',125,131.2,'Hero’da aşağı yaklaşma','Kamera','Başlangıç binası genişlerken beyaz üst yüzey yukarı gider. A sınıfı işareti ve küçük açıklama ayrı hızla okunur.',[I('Bina cephe ve sokak seviyesine yaklaşır.',[0,1]),M('Üst beyaz yüzey geri çekilir.',[0,.65]),T('A ve açıklama fotoğrafın üstünde bağımsız kalır.',[0,1])],'Kamera yönü, binanın gündelik erişim alanına götürmeli; ölçek sadece büyüklük etkisi için kullanılmamalı.'),
 c('concept',131.2,137.2,'Koyu kavram paneli ve model','Katman','Koyu basamaklı panel binanın üstüne gelir; büyük açıklama cümlesi ve küçük dönen model yeni kompozisyona yerleşir.',[I('Bina görüntüsü panel arkasında görünmeye devam eder.',[0,.5]),M('Koyu basamaklı yüzey yeni metin sahnesini taşır.',[0,1]),T('Büyük açıklama satır satır okunur; model onun altına yerleşir.',[.2,1])],'Yeni metin sahnesi giriş fotoğrafının anlamını devam ettirmeli.'),
 c('paired-images',137.2,141.4,'İki mimari detay yan yana','Paralaks','Cepheye yakın iki görüntü yan yana yerleşir. Üst metin tek bölgede, iki görüntü kendi kadrajlarında ilerler.',[I('Sol ve sağ mimari detay iki ayrı pencere oluşturur.',[0,1],[0,32,100,68]),T('Küçük açıklama üstte ortak bağlamı taşır.',[0,1],[40,0,50,27]),M('Koyu zemin iki görüntüyü birleştiren boşluğu kurar.',[0,1])],'İki yakın kadrajı aynı mimari fikri göstermek için seç; alakasız iki resmi sadece yana koyma.'),
 c('model',141.4,147.4,'Model etrafında açı ve sayısal bilgi','Kamera','Koyu modelin etrafındaki görüş açısı değişir. 6–7–8, 53 300 ve 2026 bilgileri farklı kamera durumlarıyla eşleşir.',[I('Modelin görüş açısı ve ölçeği kaydırma boyunca değişir.',[0,1]),T('Büyük sayı, açıklaması ve model konumu birbirine bağlıdır.',[0,1],[0,56,100,40]),U('Sabit üst navigasyon model sahnesinde de görünür kalır.',[0,1])],'Sayısal bilgi kamera durumuyla birlikte okunmalı; modelin her dönüşüne anlamsız bir sayı ekleme.'),
 c('location-collage',147.4,153.3,'Modelden ulaşım kolajına','Katman','Bina modelinden gerçek bina kadrajına geçilir; location paneli, iş insanı görüntüsü ve ulaşım sahneleri kademeli yüzeylerle sırayla açılır.',[I('Bina, iş insanı ve yol sahnesi farklı görüntü katmanlarıdır.',[0,1]),M('Basamaklı kenarlar gelen görüntüyü ve bilgi panelini bağlar.',[0,1]),T('Location, havaalanı ve konut bağlamları koyu panellerde okunur.',[0,1])],'Katmanlı kolajın her görüntüsü anlatıdaki bir bilgiye karşılık gelmeli.'),
 c('video-story',153.3,165.8,'Tam video ve ileri–geri katmanlar','Video','Araç içi film kadrajı doldurur. Beyaz metin yüzeyi alttan gelir; kullanıcı geri hareketinde vinç ve koyu paneli yeniden gösterir.',[I('Araç içi görüntü kendi zamanında oynar; kayıt içinde scroll da değişir.',[0,1]),M('Beyaz basamaklı metin yüzeyi alttan videonun üstüne gelir.',[.2,1]),T('Ulaşım cümlesi yeni beyaz yüzeyde açılır.',[.25,1])],'Kaynak videonun kendi oynama zamanı ile scroll’un maske hareketini ayrı sistemler olarak incele; her video scroll-scrub değildir.'),
 c('map-entry',165.8,173,'Video → harita ve sayaç kartı','Maske','Beyaz bilgi paneli videosunun önünden geçer; arkada koyu harita belirir. Harita, nokta sistemi ve 8 dakika kartı yeni sahneyi kurar.',[I('Koyu harita yeni tam ekran zemin olur.',[.3,1]),M('Beyaz basamaklı kart eski videodan yeni haritaya geçişi taşır.',[0,1]),T('8 ve ulaşım açıklaması kartta görünür.',[.45,1]),U('Harita noktaları ayrı etkileşim hedefleridir.',[.5,1])],'Haritaya giriş, önceki ulaşım anlatısının devamı olarak kurulmalı.'),
 c('map-tabs',173,183.5,'Harita pinleri ve 8 → 18 kartı','Etkileşim','Haritada nokta hover’ı ve ulaşım süresi kartının değişimi görülür. Harita zemini dururken kart ve vurgu değişir.',[I('Harita temel kadrajını korur.',[0,1]),T('Süre ve hedef bilgisi birlikte değişir.',[0,1],[0,57,31,42]),U('Pin ve kısa tooltip karttan bağımsız bir odaktır.',[0,1])],'Pinler ile filtre kartını aynı seçime bağla; hangi ulaşım hedefinin anlatıldığını açık tut.'),
 c('lifestyle',183.5,192.5,'Yaşam kolajı: kart içindeki sporcu','Katman','Geniş koşucu görüntüsü ve öndeki koyu kart birbirine göre hareket eder. Kayakçı görüntüsü yeni bir seçim olarak kart içinde değişir.',[I('Arka geniş spor görüntüsü ve ön kart farklı kadrajlardır.',[0,1]),M('Koyu basamaklı kart görseli kendi içinde keser.',[0,1],[0,23,48,70]),T('Sağ açıklama kolajın ortak bağlamını korur.',[0,1])],'Bütün fotoğrafı aynı yönde kaydırmak yerine ön plan ve arka planın farklı görevleri olmalı.'),
 c('master-plan',192.5,201.4,'Yaşamdan master plan’a','Kadraj','Beyaz model sahnesi yaşam kolajının üstüne gelir. Bütün bina ve merkezdeki 3D CTA okunur; ardından mimari cephe sahnesi yaklaşır.',[I('Bütün model beyaz zemin üzerinde ölçeğine oturur.',[.2,1],[15,20,70,66]),M('Beyaz sahne alttan koyu yaşam bölümünü örter.',[0,.65]),U('3D CTA modelin ortasına yerleşir.',[.25,1],[43,37,17,33])],'Modelin bütünlüğünü önce göster. Sonraki CTA veya kat anlatısı tam modelin konumunu kaybetmemeli.'),
 c('architecture',201.4,209,'Cephe, koyu kart ve açılan görüntü','Maske','Cephe fotoğrafı büyür; koyu ARCHITECTURE kartı geçer ve daha geniş bina kadrajı açılır. Aynı basamak dili iki yüzeyde de kullanılır.',[I('Cephe fotoğrafı kendi kadrajında yakınlaşır.',[0,1]),M('Koyu kart görüntü alanını örtüp yeniden açar.',[.18,.85],[0,41,87,53]),T('ARCHITECTURE ve küçük bilgiler kartın içinde açılır.',[.2,.85])],'Metin panelinin girişini fotoğrafın esas çizgileriyle çakıştır; binanın kimliğini tamamen örten süreyi kontrol et.'),
 c('architect-quote',209,214.3,'Mimar kartı → lobi','Katman','Mimarın beyaz bilgi kartı, dış cephe ve lobi görüntüsü arasında durur. Lobi fotoğrafı büyüyerek sonraki beyaz bölüme bağlanır.',[I('Dış cepheden sıcak lobi fotoğrafına geçilir.',[0,1]),M('Beyaz basamaklı bilgi kartı ön katman olur.',[0,.8],[0,23,35,70]),T('Mimar kimliği ve lobi başlığı yeni kadrajlarda açılır.',[0,1])],'Bilgi kartı iki farklı mekân görüntüsü arasındaki ilişkiyi açıklamalı.'),
 c('materials',214.3,220.6,'Malzeme parçaları: ayrışmış kompozisyon','Malzeme','Beyaz zeminde taş, panel, çubuk ve küreler ayrı bir kompozisyon oluşturur; açıklama ve sonraki lobi fotoğrafı onun çevresinde görünür.',[I('Malzeme parçaları birbirinden ayrılmış halde okunur.',[0,1],[17,25,68,66]),M('Beyaz zemin boşluğu malzeme hiyerarşisini kurar.',[0,1]),T('Malzeme ve lobi açıklaması parçalardan ayrı alandadır.',[0,1])],'Ölçü, malzeme ve strüktürü fiziksel anlamlarıyla göster; dekor parçalarıyla mimari bilgiyi karıştırma.'),
 c('lobby',220.6,230,'Lobi görseli, sayılar ve galeri','Galeri','Lobi görseli üstten yerleşir; 4, 12, 16 bilgileri ve altındaki resepsiyon galerisi görünür. Fotoğraf şeridi yana açılır.',[I('Lobi fotoğrafı ve resepsiyon galerisi ayrı pencerelerdir.',[0,1]),T('Dört giriş, tavan yüksekliği ve asansör bilgisi beyaz alanda okunur.',[.15,.65]),U('Galeri sayacı ve okları fotoğraf altındadır.',[.4,1])],'Büyük mekân fotoğrafını sayısal bilgiyle birlikte okut; galeriye geçişte aynı mekânın ölçeği korunmalı.'),
 c('offices',230,237.7,'İnsan videosu → çalışma alanı','Video','İnsan videosunun üzerine koyu offices kartı gelir. Sonra çalışma alanı fotoğrafı ve küçük kontrol kartı aynı katman dilini devam ettirir.',[I('İnsan filmi ve çalışma alanı fotoğrafı art arda görünür.',[0,1]),M('Koyu basamaklı kart öne gelip yeni sahneyi taşır.',[0,.75]),T('Offices ve çalışma alanı açıklaması kartın içinde kalır.',[0,1]),U('Küçük galeri/CTA kontrolleri fotoğrafın üstünde yerleşir.',[.4,1])],'İnsan görüntüsünün mekân fotoğrafına geçişi, orada yaşanan eylemi açıklamalı.'),
 c('technology',237.7,244,'Servis kartları → teknoloji','Katman','İki hizmet kartı, tesisat görüntüsü ve çizgisel teknik görsel sırayla açılır. Koyu zemin ortak bağlayıcı olarak kalır.',[I('Tesisat fotoğrafından teknik çizime geçilir.',[.3,1]),M('Basamaklı kartlar içeriği koyu zemin üzerinde böler.',[0,1]),T('Technology ve teknik açıklama ayrı okumalar olarak görünür.',[.25,1])],'Teknik bilgiler için sakin bir görsel dil seç; her altyapı özelliğine aynı büyük kamera dalışını verme.'),
 c('infrastructure',244,260.8,'Altyapı: çok görüntülü basamaklı akış','Katman','Aerial, market, restoran, kafe, sağlık, spor ve ortak alan görüntüleri art arda girer. Koyu etiket kartları ve ikonlar değişirken zemin sürekliliği korunur.',[I('Her görüntü yeni bir gündelik kullanım başlığına karşılık gelir.',[0,1]),M('Basamaklı kesimler bir görüntüden diğerine aynı yönü korur.',[0,1]),T('Retail, restaurant, café, medical, fitness ve communal etiketi bağlamı taşır.',[0,1]),U('Kart ikonları kendi başlıklarıyla birlikte değişir.',[0,1])],'Sıralı fotoğrafların her biri farklı bilgi taşımalı. Aynı resmi çok kez göstererek uzunluk üretme.'),
 c('team',260.8,264.8,'Ortak alan → ekip kartları','Kadraj','Son ortak alan galerisinden beyaz OUR TEAM sahnesine geçilir. Üç koyu kart ve ajans isimleri yan yana yerleşir.',[I('Ortak alan fotoğrafı üstten çıkar.',[0,.45]),M('Beyaz bölüm ve üç koyu kart aynı grid dilini taşır.',[.2,1]),T('OUR TEAM ve ekip isimleri kart hiyerarşisini tamamlar.',[.25,1])],'Kapanışta büyük fotoğraf akışını sakin bir bilgi grid’ine bağla. Bu desktop kaydı footer’a ulaşmadan biter.')
];

const likovaMobile=[
 c('identity',3,7.5,'Mobil yükleme: model ve beyaz kart','Açılış','Dikey koyu ekranda küçük bina modeli ve basamaklı beyaz logo kartı görünür. Yüzde tamamlanınca model gider ve hero açılır.',[I('Model dar kadrajda bütün olarak görünür.',[0,.75]),M('Beyaz logo kartı modelin önündedir.',[0,1],[25,33,50,25]),T('Logo ve yüzde kart içinde kalır.',[0,1])],'Yükleme ekranındaki model küçük olsa da tamamı görünmeli; beyaz kart yüzdesinin konumu sabit kalmalı.'),
 c('hero',7.5,13,'Mobil basamaklı hero','Maske','Beyaz logo yüzeyi yukarı çıkar; altındaki bina görüntüsü ve A sınıfı işareti dikey sırada okunur.',[I('Bina fotoğrafı dikey görüntüye göre yeniden kadrajlanır.',[0,1]),M('Beyaz üst yüzey kademeli kenarıyla açılır.',[0,.8]),T('Logo, küçük açıklama ve A işareti ayrı düşey alanlarda kalır.',[0,1])],'Mobil kadrajın üstteki metin payını başlangıçta çöz; sonradan fit yapan bir görüntü büyümesi ekleme.'),
 c('concept-preview',13,17,'Koyu konsept panelinin ilk görünümü','Katman','Bina görüntüsü altta kalırken koyu basamaklı konsept kartı üzerine gelir. Büyük açıklama ve model burada yeni bir metin sahnesi oluşturur.',[I('Bina fotoğrafı kart arkasında devam eder.',[0,.7]),M('Koyu kart alttan görüntüyü örter.',[0,1]),T('Büyük açıklama tek kolonda açılır.',[.2,1])],'Bilgi sahnesini mobilde ayrıca sırala; desktop’ın yatay boşluklarını olduğu gibi küçültme.'),
 c('hero-return',17,22.6,'Hero’ya geri scroll','Ters akış','Kullanıcı yukarı kaydırır; koyu konsept paneli çıkar, bina ve beyaz logo yüzeyi geri gelir.',[I('Bina kadrajı önceki duruma geri döner.',[0,1]),M('Koyu kart çekilir, beyaz üst yüzey geri görünür.',[0,1]),T('A sınıfı işareti yeniden okunur.',[0,1])],'Geri kaydırmada scene reset yerine aynı kayıtlı duruma doğru dönüş gerekir.'),
 c('menu',22.6,28.4,'Mobil menü tam yüzey açılır','Etkileşim','Beyaz menü tam genişlikte açılır. Bölüm listesi, çizgisel bina ve iki alt CTA dikey hiyerarşide görünür; kapanınca hero’ya dönülür.',[M('Desktop yan paneli burada tam ekran beyaz yüzeydir.',[0,1]),T('Bölüm isimleri tek kolon; plan çizimi alt sıradadır.',[.15,.9],[3,28,94,64]),U('X, bölüm linkleri ve iki CTA ayrı dokunma alanlarıdır.',[0,1])],'Mobil menü içerik hiyerarşisini ve kapatmayı korumalı; desktop yan panelini küçültmek yetmez.'),
 c('paired-images',28.4,32.4,'Metin ve cephe detayı','Paralaks','Koyu açıklama metni ve yakın cephe fotoğrafı art arda okunur. Desktop’ın yan yana cephe görüntülerine karşılık tek kolon kullanılır.',[I('Cephe yakın planı metnin altında görünür.',[0,1]),T('Açıklama küçük ama tek genişlikte okunur.',[0,1],[4,11,92,35]),M('Koyu zemin açıklama ile fotoğrafı birleştirir.',[0,1])],'Mobilde ayrıntı fotoğrafının yeterli yüksekliğini koru; masaüstü ikili görüntüyü minyatürleştirme.'),
 c('model',32.4,40.8,'Mobil model ve büyük sayılar','Kamera','Modelin farklı açıları boyunca 6–7–8, 53 300 ve 2026 bilgileri değişir. Sayılar alt bölgede görünür.',[I('Model mobil kadrajda görüş açısını değiştirir.',[0,1]),T('Büyük sayı ve açıklaması aynı kamera durumuna bağlıdır.',[0,1],[2,68,96,30]),U('Üst navigasyon model sahnesinde ince bir banttır.',[0,1])],'Modelin kadrajda bütünlüğünü ve bilgi yazılarının çakışmadığını her açı için kontrol et.'),
 c('location-collage',40.8,47.2,'Model → location → insan','Katman','Modelden renkli bina görünümüne, koyu location paneline ve iş insanı görüntüsüne geçilir. Katmanlar dikey sırada açılır.',[I('Bina ve insan görüntüleri yeni başlıklarla eşleşir.',[0,1]),M('Basamaklı paneller fotoğrafın önüne gelir.',[0,1]),T('Ulaşım açıklaması panel altında okunur.',[0,1])],'Dikey kolajda fotoğraf ve açıklama eşleşmesi korunmalı; tek scroll’da çok sayıda bilgi üst üste binmemeli.'),
 c('video-story',47.2,51.8,'Araç içi video ve beyaz metin','Video','Araç içi film mobil ekranı doldurur. Beyaz basamaklı açıklama sahnesi alttan gelerek videoyu örter.',[I('Araç içi film kendi hareketini sürdürür.',[0,1]),M('Beyaz panel videonun üstüne alttan gelir.',[.45,1]),T('Ulaşım cümlesi beyaz alanda açılır.',[.6,1])],'Film oynatımı ve sayfanın hareketi farklı katmanlardır; filmi scroll hızıyla yapay biçimde hızlandırma.'),
 c('map-entry',51.8,54.6,'Harita ve süre kartı','Maske','Koyu harita üstte, büyük 8 dakika kartı altta görünür. Fotoğraf akışı yerini okunabilir harita bilgisinin dikey düzenine bırakır.',[I('Harita kendi yüksekliğini kullanır.',[0,1],[0,0,100,47]),M('Beyaz süre kartı alt katman olarak açılır.',[0,1],[0,37,100,46]),T('Sayı ve hedef açıklaması beyaz kart içindedir.',[.2,1])],'Mobil harita ile bilgi kartını çakıştırma; ikisine de okunur ayrı alan bırak.'),
 c('map-tabs',54.6,58.8,'8 → 5 → 18 ulaşım kartı','Etkileşim','Ulaşım seçimi değiştikçe süre ve hedef açıklaması birlikte değişir. Harita yeni seçimin arka bağlamı olarak kalır.',[I('Harita kadrajı aynı yüzeyde kalır.',[0,1]),T('Süre ve hedef adı aynı seçimle değişir.',[0,1],[2,30,96,59]),U('Alt kontrol çizgisi yeni kart seçimini izler.',[0,1])],'Rakamı başlıktan bağımsız değiştirme; harita, açıklama ve seçili işaret aynı bilgi durumunu taşımalı.'),
 c('lifestyle',58.8,65.2,'Mobil yaşam: koşu ve kayak','Galeri','Koyu açıklama ve sporcu fotoğrafı dikey sırada görünür. Kayakçı seçimi resimle birlikte açıklamayı değiştirir.',[I('Koşucu ve kayakçı aynı resim penceresini kullanır.',[0,1],[0,45,100,55]),T('Her spor görüntüsünün kendi açıklaması üstte kalır.',[0,1],[3,4,94,39]),U('Sayaç ve oklar açıklamayla fotoğraf arasındadır.',[0,1])],'Görsel değişimi bir yeni yaşam bilgisini anlatmalı; sadece ikinci fotoğraf var diye slayt ekleme.'),
 c('master-plan',65.2,68.7,'Bütün bina ve 3D çağrısı','Kadraj','Beyaz master plan sahnesinde bütün bina modeli ve ortadaki koyu 3D CTA görünür. Sonraki cephe fotoğrafı alttan gelir.',[I('Bütün model dar dikey ekranda gösterilir.',[0,1]),M('Beyaz zemin önceki koyu bölümü devralır.',[0,1]),U('3D CTA modelin önündedir; kayıtta açılmaz.',[.1,1])],'Modelin tamamını önce okut. Açılmayan 3D arayüzü bu kayıtla incelenmiş sayma.'),
 c('architecture',68.7,71.4,'Mimari fotoğraf ve koyu kart','Maske','Cephe fotoğrafı gelirken koyu kademeli kart önüne açılır. Alt metin ve yeni mimari görüntü bir sonraki bölüme geçer.',[I('Cephe fotoğrafı üst katmanda görünür.',[0,1]),M('Koyu kart fotoğrafın altını kademeli örter.',[0,1]),T('Mimari açıklama yeni kart içinde görünür.',[.15,1])],'Bina fotoğrafının tanınan çizgilerini maske hareketi boyunca koru.'),
 c('architect-quote',71.4,73.2,'Mimarın beyaz kartı','Katman','Mimar bilgisi beyaz kartta okunur, lobi fotoğrafı altta görünmeye başlar.',[I('Dış cepheden lobi görüntüsüne geçilir.',[0,1]),M('Beyaz bilgi kartı iki görseli birbirine bağlar.',[0,1]),T('Mimar adı kartın üst kısmında kalır.',[0,1])],'Bilgi yüzeyini görsel geçişinde bir boşluk değil, anlatım köprüsü olarak kullan.'),
 c('materials',73.2,80.8,'Malzemeler ve geri–ileri okuma','Malzeme','Beyaz malzeme kompozisyonu görünür; kullanıcı lobiye iner ve geri dönerek aynı parçaları tekrar gösterir.',[I('Panel, küre ve malzeme parçaları bütün kompozisyonda kalır.',[0,1]),T('Malzeme açıklaması mobilde kompozisyonun üstü ve altındadır.',[0,1]),M('Beyaz zemin sonraki fotoğraf için sürekli alan oluşturur.',[0,1])],'Teknik görsel ileri ve geri okunduğunda da bütün kalmalı; oran değiştiren ek fit animasyonu kullanılmamalı.'),
 c('lobby',80.8,88.8,'Lobi bilgisi ve mobil galeri','Galeri','Lobi resmi, açıklama, 4–12–16 bilgileri ve resepsiyon galerisi dikey sırada okunur. Galeri fotoğrafı seçimi ayrıca gösterilir.',[I('Lobi ve resepsiyon fotoğrafları ayrı içerik pencereleri oluşturur.',[0,1]),T('Sayılar bir satıra sıkıştırılmaz; mobilde ayrı satırlarda yerleşir.',[.2,.7]),U('Galeri kontrolleri fotoğraf altında kalır.',[.5,1])],'Mobil sayısal bilgi grid’ini yeniden düzenle; tek satırda aşırı küçük tipografiyle okunurluğu kaybetme.'),
 c('offices',88.8,94.7,'Ofis videosu ve hizmet kartları','Video','İnsan filmi, offices kartı ve çalışma alanı resmi art arda gelir. Hizmet kartları beyaz ayırıcılarla sıralanır.',[I('İnsan hareketi ve mekân görüntüsü farklı yüzeylerdir.',[0,1]),M('Koyu basamaklı kartlar dar ekranda tek sıra olur.',[0,1]),T('Ofis ve hizmet bilgileri her kartın içinde kalır.',[0,1])],'Fotoğraftaki eylemden mekân bilgisine geçiş anlaşılır bir sırayla kurulmalı.'),
 c('technology',94.7,98.7,'Teknoloji ve enerji kartı','Katman','Tesisat görseli, technology yazısı ve enerji kartı koyu bölümde açılır. Görüntü ve bilgiler dikey olarak ilerler.',[I('Teknik fotoğraf üstte kendi kadrajında kalır.',[0,1]),T('Technology ve açıklama görselin altında okunur.',[0,1]),M('Beyaz enerji kartı koyu zeminden ayrılır.',[.5,1])],'Teknik bölümlerin kontrastı, günlük yaşam fotoğraflarından farklı ama aynı sistem içinde olmalı.'),
 c('infrastructure',98.7,102.3,'Aerial → market → ekip','Katman','Geniş aerial görüntüden market fotoğrafına geçilir; sonrasında beyaz ekip bölümü gelir. Desktop’ın daha uzun altyapı dizisinin burada bir kısmı kaydedilmiştir.',[I('Aerial ve market görüntüsü farklı gündelik bağlamlar taşır.',[0,1]),M('Koyu etiket kartı ve beyaz ekip yüzeyi sırayla öne gelir.',[0,1]),T('Retail ve ekip başlıkları kendi sahnelerinde okunur.',[0,1])],'Kayıtta görülmeyen restoran, kafe veya sağlık geçişlerini mobilde varmış gibi bu klibe ekleme.'),
 c('team',102.3,107,'Ekip kartları tek kolonda','Kadraj','Desktop’ın üç yan yana kartı mobilde tek akışa dönüşür. Marka isimleri büyük koyu kartlarda sırayla okunur.',[M('Koyu kartlar beyaz zemin üzerinde dikey sıralanır.',[0,1]),T('OUR TEAM ve ekip kimlikleri her kart içinde kalır.',[0,1]),U('Kart başlıkları ve detay işaretleri ayrı küçük kontroldür.',[0,1])],'Bir desktop grid’ini mobilde yeniden sırala; kartların anlamlı büyüklüğünü koru.'),
 c('footer',107,110,'Mobil footer ve kapanış','Kadraj','Ekip kartı çıkar; LIKOVA, açılış saatleri, contact düğmesi ve alt bilgiler koyu footer içinde görünür.',[M('Koyu footer ve beyaz basamaklı üst sınır ortak kompozisyondur.',[0,1]),T('Marka, saat ve hukuki alt bilgi ayrı hiyerarşilerde okunur.',[0,1]),U('Contact düğmesi yeni sahnenin ana kontrolüdür.',[.25,1])],'Kapanışta linkleri ve ikincil bilgiyi açık sırala; büyük fotoğraf akışının ardından daha sakin bir okuma kur.')
];

const deviceNotes={
 era:'Desktop’ta konsept ve konum yatay bir rayda ilerler; mobilde başlık, fotoğraf ve açıklama düşey sıraya dönüşür. Mimari iki-pencere birleşmesi desktop kaydında vardır; mobilde doğrudan mimari fotoğraf girişi görülür. Footer kadrajı iki ekranda farklıdır.',
 likova:'Desktop’ta çoklu görüntüler ve bilgi kartları yan yana kompozisyon kurar; mobilde aynı sahneler ayrı düşey yüzeylere dönüşür. Menü desktop’ta yan panel, mobilde tam yüzeydir. Büyük sayılar ve ekip grid’i yeniden sıralanır.'
};
const flow=(project,device,offset,duration,scenes,coverage,gaps)=>({id:`${project}-${device}`,project,device,offset,duration,fps:60,width:device==='desktop'?1920:426,height:device==='desktop'?1050:636,video:`./assets/casestudy2/${project}/${device}.mp4`,source:project==='era'?'2026-10-05 13-16-27.mp4':'2026-10-05 13-20-35.mp4',viewport:device==='desktop'?'Desktop · 1920 × 1050':'Mobil emülasyon · 459 × 686',deviceNote:deviceNotes[project],coverage,gaps,scenes:scenes.map((s,i)=>({...s,id:i+1,start:+(s.sourceStart-offset).toFixed(3),end:+(s.sourceEnd-offset).toFixed(3),duration:+(s.sourceEnd-s.sourceStart).toFixed(3)}))});
export const FLOWS={
 ...ACTIVE_FLOWS,
 'era-desktop':flow('era','desktop',3,148,eraDesktop,'Ana sayfanın açılışı, pinler, bütün ana scroll akışı, footer ve ters scroll; ardından apartments listesi, daire detayı ve lightbox kaydedilmiş. Browser çubukları ve OBS başlangıcı kadraj dışında bırakıldı.','Gündüz/gece seçimi, Book a call formu ve accordion açılışı bu kayıtta gösterilmedi; bunlar için uydurma klip eklenmedi.'),
 'era-mobile':flow('era','mobile',160,78,eraMobile,'Ana sayfa hero’dan footer’a, neden ve amenity slaytları, iç galeri ve ters scroll kaydedilmiş. Chrome responsive mode 459 × 686; gerçek telefon cihaz kaydı değildir.','Bu bölüm hero açıkken başlar; mobil preloader, menü açılışı, pin sheet ve sayfalar arası gezinme gösterilmemiş.'),
 'likova-desktop':flow('likova','desktop',113.5,151.3,likovaDesktop,'Açılış, menü, model kamera akışı, location/harita, lifestyle, master plan, mimari, lobi, offices, teknoloji, altyapı ve ekip bölümü kaydedilmiş.','Desktop footer, seçilebilir 3D master plan arayüzü ve ofis seçim paneli bu kayıtta açılmamış. Kayıt ekip sahnesinde kesildi.'),
 'likova-mobile':flow('likova','mobile',3,107,likovaMobile,'Mobil açılış, menü, model, ulaşım, harita, lifestyle, master plan, mimari, lobi, offices, teknoloji, altyapının bir bölümü, ekip ve footer kaydedilmiş. Chrome responsive emülasyonudur.','3D master plan butonu ve ofis seçim arayüzü açılmamış; altyapının bazı alt fotoğrafları hızlı scroll sırasında atlanmış.')
};
export function clampTime(time,scene,fps=60){return Math.max(scene.start,Math.min(scene.end-1/fps,time));}
export function sceneAt(flow,time){return flow.scenes.find(s=>time>=s.start&&time<s.end)||flow.scenes[time>=flow.duration?flow.scenes.length-1:0];}
export function counterpart(flow,scene){return FLOWS[`${flow.project}-${flow.device==='desktop'?'mobile':'desktop'}`].scenes.find(s=>s.key===scene.key)||null;}
