from pathlib import Path
import json,struct
W=Path(r'C:\Users\yigit\angora-tur10');R=Path(r'C:\Users\yigit\Downloads\angora-main (2)\angora-main')
g=(R/'build/web/26092026/EKLER.glb').read_bytes();ln,typ=struct.unpack_from('<II',g,12);j=json.loads(g[20:20+ln]);names=[n.get('name','') for n in j['nodes']]
bad=[n for n in names if n.startswith(('107_','ARSIV')) or 'yatak' in n.lower()]
assert not bad,bad
report={'dugum':len(names),'arsiv_yatak_dugum':bad,'kontrol_fotolari':[4,13,15,17,18,19,21,29,34,40,42,44,47],'kaynak_blend_degistirildi':False,'not':'EKLER çalışma dosyası ve ayrı silme kutuları kullanıldı.'}
(W/'adim03-dogrulama.json').write_text(json.dumps(report,ensure_ascii=False,indent=1),encoding='utf-8')
audit={
4:['DÜZELTİLDİ: Duvar lekeleri temizlendi; parke gerçek fotoğraf kesitiyle değiştirildi.','KALDI: Mevcut koltuk/masa oranları ve avize ayrıntıları; mobilya bu adımda kapsam dışı, armatür M5 işi.','DÜZELTİLDİ: Ortak merdiven maskesi ve malzemeler bu açıdan yeniden denetlendi.','KALDI: Mevcut mobilyaların fotoğrafla oran eşleşmesi; yeni mobilya üretilmedi.'],
13:['DÜZELTİLDİ: Fotoğraf parkesi ve lekesiz krem duvar uygulandı.','KALDI: Desenli perde M4, üçlü spot M5; yatak kullanıcı talimatıyla kontrol/EKLER dışında.','DÜZELTİLDİ: Arşiv ve eski yatak kalıntısı kaldırıldı.','KALDI: Pencere çevresi/perde düzeni M4 adımında ele alınacak.'],
15:['DÜZELTİLDİ: Ceviz malzemesi güncellendi; kontrolün pozlama üst sınırı artırıldı.','KALDI: Raf içeriği, paspas ve küçük aksesuarlar; bu adımın altı düzeltmesinde değiller.','KALDI: Duş ve mevcut tesisatın fotoğrafa göre tam konum kontrolü; bu adımda yeniden modellenmedi.','KALDI: Banyo kaplaması ve duş oranları fotoğraftakiyle aynı değil; mevcut referans banyo değişmedi.'],
17:['DÜZELTİLDİ: Pembe düz kapı yerine gerçek ceviz dokusu ve paneller; krem duvar/parkede fotoğraf kaynağı.','DÜZELTİLDİ: Beyaz yatak ve arşiv mobilyası kontrol dışında. KALDI: Doğru armatür M5.','DÜZELTİLDİ: Eski topuz kalıntıları kaldırıldı, kanat menteşe pivotunda.','DÜZELTİLDİ: Kasa/kanat ve bitişik hol korkuluğu yeniden kontrol edildi.'],
18:['DÜZELTİLDİ: Gerçek basamak ahşabı, koyu ceviz küpeşte/kapı, lekesiz krem duvar.','KALDI: Fotoğraftaki zincirli armatür/aplik ayrıntıları M5.','DÜZELTİLDİ: Eski beyaz INTERIOR merdiven kalıntısı ve duvara saçılmış pirinç temizlendi.','DÜZELTİLDİ: Birinci kat için ayrı C/S tekrar aralığı ve bordür; galeri L kenarında. Ölçüler fotoğraftan yaklaşık.'],
19:['DÜZELTİLDİ: Ahşap zemin ve duvar boya malzemesi yenilendi.','KALDI: Mevcut yatak/komodin fotoğraftaki mobilya değil; mobilya bu adımın dışında.','KALDI: Perde ve radyatörün bu odadaki varyantı M4/M6.','KALDI: Mevcut mobilya oranları; bu adımda yeni mobilya üretilmedi.'],
21:['DÜZELTİLDİ: Karo, dolap, tezgâh ve seramik için ayrı gerçek fotoğraf kesitleri ve kutular.','KALDI: Mutfaktaki diğer radyatör M6; priz/cihaz ayrıntıları mevcut modelde farklı.','DÜZELTİLDİ: Tezgâh ve duvar seramiği ortak X malzemesi kutuyla ayrıldı.','KALDI: Mevcut dolap/ocak yerleşimi ve model oranları; bu adımda mutfak mobilyası yeniden yapılmadı.'],
29:['DÜZELTİLDİ: Cevizde gri panel şeritleri kaldırıldı, zemin fotoğraf ahşabıyla yenilendi.','KALDI: Duvar aplikleri ve interkom gibi küçük nesneler; M5/sonraki modül kapsamı.','DÜZELTİLDİ: Kamera geri/aşağı ayarlandı; kullanıcı onayıyla yalnız yerel kapı üstü/yan duvar EKLER ile değiştirildi.','DÜZELTİLDİ: Kapıya çapraz giren açıklık kapatıldı; pah kırılmış geçiş ve çatıya özel zambak uçlu korkuluk. Tam fotoğraf izdüşümü iddia edilmiyor.'],
34:['DÜZELTİLDİ: Ceviz panel dokusu, koyu küpeşte ve gerçek parke.','KALDI: Tavan/duvar armatürünün ayrıntıları M5.','DÜZELTİLDİ: Banyo kanadı kasaya menteşeden bağlı; eski beyaz merdiven kalıntısı temizlendi.','DÜZELTİLDİ: 18 ile ortak fiziksel galeri iki açıdan denetlendi; iri kapalı daire yerine C/S kıvrımları.'],
40:['DÜZELTİLDİ: Kasa/kapı cevizi ve karo; beyaz radyatör.','DÜZELTİLDİ: Dikey radyatör eklendi. KALDI: Sandalye kapsam dışı; interkom/tavan armatürü ayrıntıları henüz yapılmadı.','DÜZELTİLDİ: Camlı kanadın açılma yönü antre içine alındı; dış kapı kasa bini eklendi.','DÜZELTİLDİ: 42 ile aynı radyatörün tek fiziksel yerleşimi doğrulandı; ayrı kopya oluşturulmadı.'],
42:['DÜZELTİLDİ: Gri eşik yerine aynı yer karosu; koyu ceviz kasa ve beyaz radyatör.','DÜZELTİLDİ: Dikey radyatör, vana ve bağlantı boruları. KALDI: Sandalyeler mobilya kapsamı dışında.','DÜZELTİLDİ: Galeri korkuluğu döşeme boşluğunun sol kenarına oturtuldu; camlı kapı radyatörü kapatmıyor.','DÜZELTİLDİ: Girişe özgü tekrar/dikme ve küçük kıvrım bordürü; oda ortasından geçen çapraz yerleşim kaldırıldı.'],
44:['DÜZELTİLDİ: Düz koyu garaj kapısı, siyah kol ve fotoğraf ahşabı.','KALDI: Garajdaki depolama eşyaları ve raf içerikleri; mobilya/aksesuar bu adımda üretilmedi.','DÜZELTİLDİ: Kapalı kanat konumu korunup yeni malzemeyle denetlendi.','KALDI: Depolama mobilyası/kadraj oranları referanstan farklı; mevcut model korundu.'],
47:['DÜZELTİLDİ: Turuncu düz basamak yerine fotoğraf ahşabı ve koyu küpeşte.','KALDI: Sahanlık aynası/aplik ayrıntıları bu adımda yapılmadı.','DÜZELTİLDİ: Ray ölçümüyle saptanan Simple White Wall / interior.002 eski merdiven yüzleri kaldırıldı.','DÜZELTİLDİ: Bodrumun korkuluğu dış kenarda ve ayrı dar kıvrımlı varyant; diğer kat kopyası değil.']}
s='\n## Adım 03 · korkuluk deseni + eksikler — mevcut haliyle kapatıldı\n\nKullanıcının son talimatıyla ek düzeltme yapılmadan bu kontrol noktası yayımlanmıştır; bütün farkların çözüldüğü iddia edilmez. Yeni kusurlar Adım 04 ilk işleri olarak aşağıya kaydedildi. Bundan sonra yeni kusur düzeltmesine başlamadan mevcut adım pushlanacak; adım başına üst sınır 30 dakika.\n\nCeviz/parke/merdiven/duvar rengi ve albedo Adım 04 işidir; Adım 03 tamamlananlarına dahil değildir. Mevcut render ve GLB ara malzeme denemeleri içerir; bunlar onaylanmış renk sonucu sayılmaz. Yerel doku üretim kodları ve kaynak kesitleri korunmuştur.\n\n### Adım 04 ilk işler — KALDI\n\n- KALDI: Foto 47 bodrum basamaklarının yanındaki beyaz kalıntı. Ray testi interior.002 / Simple White Wall sonucunu verdi; GLB malzeme incelemesi bunun BUILDING katmanında olduğunu doğruladı. Önceki mobilya katmanı maskesi etkisiz kaldı; mimari katmandaki dar bölge ayrıca ölçülerek düzeltilecek.\n- KALDI: Kapı/eşik çevresindeki beyaz ışık yarıkları (özellikle 17,34,40,44); dış kapıya bini eklenmesine rağmen tüm yarıklar kapanmadı.\n- KALDI: Foto 29 geçişte iki pahın simetrik görünümü ve fotoğrafla açıklık oranı; kapıya giren büyük çapraz boşluk giderildi fakat birebir eşleşme tamamlanmadı.\n- KALDI: Korkuluklarda fotoğrafın ince C/S kıvrım ve bağlantı ayrıntıları; yeni kat varyantları mevcut fakat birebir desen doğrulaması tamamlanmadı.\n- KALDI: Kartonpiyer birleşim izleri; fotoğraf bazında yeniden ele alınacak.\n- KALDI: Foto 15 banyo ışığı/kaplaması; pozlama artışı yalnız kontrol görünürlüğü, bitmiş aydınlatma değildir.\n- KALDI: Ceviz, parke, merdiven ahşabı ve duvar kremi: Adım 04 albedo/renk işi.\n\n### Son yerleşim doğrulaması\n\n| Yerleşim | Kendi referansı | Kontrol |\n|---|---|---|\n| Bodrum merdiveni | 47 (48 yardımcı) | 47 render; beyaz kalıntı KALDI |\n| Giriş merdiveni / galeri | 42,40 | iki açı |\n| Birinci kat / galeri | 18,34 | iki açı |\n| Çatı / son kol | 29 | kamera ve yerel duvar onayıyla |\n| Antre radyatörü | 40,42 | tek fiziksel radyatör, iki açı |\n| Camlı antre kapısı | 40,42 | açılış yönü iki açıyla düzeltildi |\n| Dış giriş kapısı 13 | 40,41 | kapalı kanat, kasa bini; alt ışık yarığı KALDI |\n| Diğer kapılar | önceki kapı tablosu | fotoğrafsız satırlar doğrulanmış sayılmaz |\n\nKorkuluk parametreleri moduller/korkuluk_motif.py içinde: yarıçap/tekrar/dikme aralığı metre. Fotoğraf oranlarından yaklaşık çıkarılmıştır; saha ölçümü ya da birebir çizgi izleme iddiası yok.\n\n'
for n,items in audit.items():
 items[0]='KALDI: Renk/albedo eşleşmesi Adım 04 kapsamıdır; bu görüntüdeki ara malzeme denemesi Adım 03 tamamlanmış işi sayılmaz.'
for n in [18,34,47]:audit[n][2]='KALDI: Eski beyaz merdiven kalıntısının mimari katmanda dar maske ile temizlenmesi Adım 04 ilk işi; önceki maske sonuç vermedi.'
for n in [17,34,40,44]:audit[n][2]+=' KALDI: Kasa/eşik çevresindeki açık renk ışık yarıkları.'
audit[29][3]='KALDI: Büyük çapraz boşluk kapatıldı; iki pahın görünüşü, açıklık oranı ve ince korkuluk deseni Adım 04 yeniden kontrolü.'
for n,items in audit.items():
 s+=f'### Foto {n:02d} — öz denetim\n\n'
 for h,v in zip(['Malzeme tonu','Fazla/eksik nesne','Kalıntı/yerleşim','Geometri/oran'],items):s+=f'- **{h}:** {v}\n'
 s+='\n'
s+='Foto 15 pozlama artışı yalnız kontrol görünürlüğü içindir; fiziksel banyo armatürünün tamamlandığı anlamına gelmez. KALDI kayıtları bütün Tur 10 için açık işleri gösterir; mobilya üretilmedi.\n'
p=W/'notlar.md';p.write_text(p.read_text(encoding='utf-8')+s,encoding='utf-8')
print(json.dumps(report,ensure_ascii=False))
