#!/usr/bin/env python3
"""Build web2-tr.html from web2.html with a Turkish string table.

Run from the repository root: python3 tools/web2-build-tr.py
Every English string in the table must still exist in web2.html; the build
fails loudly otherwise, so the two pages cannot drift apart silently.
"""
import json, pathlib, re, sys

root = pathlib.Path(__file__).resolve().parent.parent
html = (root / 'web2.html').read_text(encoding='utf-8')

T = [
 ('<html lang="en">', '<html lang="tr">'),
 ('<title>Angora 21 — A private world, within the city</title>', '<title>Angora 21 — Şehrin içinde, size ait bir dünya</title>'),
 ('content="A detached residence in Angora Evleri, Ankara: private garden, pool and four levels of living, told through a scroll-driven camera journey, original photography and registered floor plans."',
  'content="Ankara Angora Evleri’nde müstakil bir villa: özel bahçe, havuz ve dört kat. Kaydırmayla ilerleyen bir kamera yolculuğu, özgün fotoğraflar ve kayıtlı kat planlarıyla anlatılıyor."'),
 ('<meta property="og:title" content="Angora 21 — A private world, within the city">', '<meta property="og:title" content="Angora 21 — Şehrin içinde, size ait bir dünya">'),
 ('<a class="skip" href="#residence">Skip to content</a>', '<a class="skip" href="#residence">İçeriğe geç</a>'),
 ('aria-label="Angora 21 home"', 'aria-label="Angora 21 ana sayfa"'),
 ('<nav class="header-nav" aria-label="Main navigation"><a href="#residence">The residence</a><a href="#floors">Four chapters</a><a href="#atlas">Plans &amp; photos</a><a href="#life">Life in Angora</a><a class="header-cta" href="#contact">Arrange a viewing</a></nav>',
  '<nav class="header-nav" aria-label="Ana gezinme"><a href="#residence">Villa</a><a href="#floors">Dört kat</a><a href="#atlas">Planlar &amp; fotoğraflar</a><a href="#life">Angora’da yaşam</a><a class="header-cta" href="#contact">Randevu alın</a></nav>'),
 ('<span class="menu-word">Menu</span>', '<span class="menu-word">Menü</span>'),
 ('<nav aria-label="Menu">', '<nav aria-label="Menü">'),
 ('<a href="#residence"><small>01</small>The residence</a><a href="#garden"><small>02</small>Garden &amp; pool</a><a href="#spaces"><small>03</small>Inside the home</a><a href="#floors"><small>04</small>Four chapters</a><a href="#atlas"><small>05</small>Plans &amp; photographs</a><a href="#location"><small>06</small>The neighbourhood</a><a href="#life"><small>07</small>Life in Angora</a><a href="#gallery"><small>08</small>Photo collection</a><a href="#contact"><small>09</small>Arrange a viewing</a>',
  '<a href="#residence"><small>01</small>Villa</a><a href="#garden"><small>02</small>Bahçe &amp; havuz</a><a href="#spaces"><small>03</small>Evin içi</a><a href="#floors"><small>04</small>Dört kat</a><a href="#atlas"><small>05</small>Planlar &amp; fotoğraflar</a><a href="#location"><small>06</small>Mahalle</a><a href="#life"><small>07</small>Angora’da yaşam</a><a href="#gallery"><small>08</small>Fotoğraf koleksiyonu</a><a href="#contact"><small>09</small>Randevu alın</a>'),
 ('aria-label="Angora 21 introduction"', 'aria-label="Angora 21 açılış"'),
 ('aria-label="The villa at dusk"', 'aria-label="Villa akşam ışığında"'),
 ('alt="The villa and its neighbourhood at dusk"', 'alt="Villa ve çevresi akşam ışığında"'),
 ('<p class="eyebrow">A private residence · Angora Evleri, Ankara</p>', '<p class="eyebrow">Müstakil bir villa · Angora Evleri, Ankara</p>'),
 ('<p class="hero-script">A place of your own.</p>', '<p class="hero-script">Size ait bir yer.</p>'),
 ('<span class="eyebrow">01 / 03 · Arrival</span><h2>A quieter arrival.</h2><p>The garden-facing living floor opens to a covered terrace and the private pool.</p>',
  '<span class="eyebrow">01 / 03 · Varış</span><h2>Daha sakin bir varış.</h2><p>Bahçeye bakan yaşam katı, üstü kapalı terasa ve özel havuza açılır.</p>'),
 ('<span class="eyebrow">02 / 03 · Perspective</span><h2>A world of your own.</h2><p>Four levels, five bedrooms and four living spaces. A detached home with room for different generations.</p>',
  '<span class="eyebrow">02 / 03 · Perspektif</span><h2>Size ait bir dünya.</h2><p>Dört kat, beş yatak odası ve dört yaşam alanı. Farklı kuşaklara yer açan müstakil bir ev.</p>'),
 ('<span class="eyebrow">03 / 03 · Garden</span><h2>Life opens outside.</h2><p>Balconies, terrace and a private pool connect the home to its own 900 m² garden.</p>',
  '<span class="eyebrow">03 / 03 · Bahçe</span><h2>Hayat dışarı açılır.</h2><p>Balkonlar, teras ve özel havuz evi kendi 900 m²’lik bahçesine bağlar.</p>'),
 ('aria-label="Camera film chapters"', 'aria-label="Kamera filmi bölümleri"'),
 ('<span>01</span><b>Arrival</b>', '<span>01</span><b>Varış</b>'),
 ('<span>02</span><b>Perspective</b>', '<span>02</span><b>Perspektif</b>'),
 ('<span>03</span><b>Garden</b>', '<span>03</span><b>Bahçe</b>'),
 ('<a href="#residence">Scroll to discover ↓</a><button type="button" data-tour="building">Explore in 3D ↗</button>', '<a href="#residence">Keşfetmek için kaydırın ↓</a><button type="button" data-tour="building">3B’de keşfedin ↗</button>'),
 ('<span class="eyebrow">01 / The residence</span><span class="eyebrow">An established address. A personal way to live.</span>', '<span class="eyebrow">01 / Villa</span><span class="eyebrow">Yerleşik bir adres. Kişisel bir yaşam biçimi.</span>'),
 ('The space to live.<br>The freedom to<br><em>make it yours.</em>', 'Yaşayacak alan.<br>Kendinize göre<br><em>biçimlendirme özgürlüğü.</em>'),
 ('<p>On Hatırlı Sokak, in Ankara’s Angora Evleri, this detached villa brings together a private garden, a swimming pool and four distinct levels of living.</p><p>The slope of the site gives the home two different arrivals: a street-level entrance for everyday life, and a lower level that opens directly onto the terrace, garden and water.</p><p>Five bedrooms. Four living spaces. Three kitchens. Enough independence for different generations, with plenty of room to come together.</p>',
  '<p>Ankara Angora Evleri’nde, Hatırlı Sokak üzerindeki bu müstakil villa özel bahçeyi, yüzme havuzunu ve dört ayrı yaşam katını bir araya getiriyor.</p><p>Arsanın eğimi eve iki farklı giriş kazandırıyor: gündelik hayat için sokak kotunda bir giriş ve doğrudan terasa, bahçeye ve suya açılan bir alt kat.</p><p>Beş yatak odası. Dört yaşam alanı. Üç mutfak. Farklı kuşaklar için yeterli bağımsızlık, bir araya gelmek için bolca yer.</p>'),
 ('<dt>Gross interior area</dt>', '<dt>Brüt kapalı alan</dt>'), ('<dt>Net living area</dt>', '<dt>Net yaşam alanı</dt>'), ('<dt>Private garden</dt>', '<dt>Özel bahçe</dt>'), ('<dt>Bedrooms + living spaces</dt>', '<dt>Yatak odası + yaşam alanı</dt>'),
 ('<p class="note">Areas and room counts are as described in the property listing.</p>', '<p class="note">Alanlar ve oda sayıları ilan metnindeki gibidir.</p>'),
 ('alt="The villa\'s street facade and covered entrance on Hatırlı Sokak"', 'alt="Villanın Hatırlı Sokak’taki sokak cephesi ve üstü kapalı girişi"'),
 ('<figcaption>The street elevation · Hatırlı Sokak</figcaption>', '<figcaption>Sokak cephesi · Hatırlı Sokak</figcaption>'),
 ('<span class="eyebrow">Hatırlı Sokak · The street entrance</span>', '<span class="eyebrow">Hatırlı Sokak · Sokak girişi</span>'),
 ('<h2 data-reveal="lines">A quieter <em>arrival.</em></h2>', '<h2 data-reveal="lines">Daha sakin <em>bir varış.</em></h2>'),
 ('<p class="lead" data-reveal="fade">Enter from the street. Live towards the garden. The slope gives the house two front doors: one for every day, one for every summer.</p>', '<p class="lead" data-reveal="fade">Sokaktan girin. Bahçeye doğru yaşayın. Eğim eve iki kapı veriyor: biri her gün için, biri her yaz için.</p>'),
 ('<a class="text-link" href="#atlas">Discover the layout ↗</a>', '<a class="text-link" href="#atlas">Yerleşimi keşfedin ↗</a>'),
 ('aria-label="Rooms for different generations"', 'aria-label="Farklı kuşaklar için odalar"'),
 ('<span class="eyebrow">Rooms for different generations</span>', '<span class="eyebrow">Farklı kuşaklar için odalar</span>'),
 ('<h2 data-reveal="lines">A home with<br><em>room to grow.</em></h2>', '<h2 data-reveal="lines">Büyümeye<br><em>yer olan bir ev.</em></h2>'),
 ('<p data-reveal="fade">Five bedrooms across three levels. Each with its own light, its own quiet.</p>', '<p data-reveal="fade">Üç kata yayılan beş yatak odası. Her birinin kendi ışığı, kendi sessizliği.</p>'),
 ('aria-label="Three bedrooms, scroll sideways on a phone"', 'aria-label="Üç yatak odası, telefonda yana kaydırın"'),
 ('alt="A bedroom on the private first floor"', 'alt="Birinci kattaki bir yatak odası"'), ('<figcaption>01 / A bedroom of your own</figcaption>', '<figcaption>01 / Size ait bir yatak odası</figcaption>'),
 ('alt="Another first-floor bedroom, with balcony doors"', 'alt="Balkon kapılı bir başka birinci kat yatak odası"'), ('<figcaption>02 / A quiet connection outside</figcaption>', '<figcaption>02 / Dışarıyla sessiz bir bağ</figcaption>'),
 ('alt="Bedroom beneath the attic roof"', 'alt="Çatı altındaki yatak odası"'), ('<figcaption>03 / A separate world upstairs</figcaption>', '<figcaption>03 / Üst katta ayrı bir dünya</figcaption>'),
 ('alt="The complete private garden and swimming pool from above"', 'alt="Özel bahçe ve yüzme havuzu yukarıdan"'),
 ('alt="The villa, covered terrace and private swimming pool"', 'alt="Villa, üstü kapalı teras ve özel yüzme havuzu"'),
 ('alt="Mature planting and the garden path beside the villa"', 'alt="Villanın yanındaki olgun bitkiler ve bahçe yolu"'),
 ('<span class="eyebrow">02 / Life outside</span><h2>More sky.<br><em>More time.</em></h2>', '<span class="eyebrow">02 / Dışarıdaki hayat</span><h2>Daha çok gökyüzü.<br><em>Daha çok zaman.</em></h2>'),
 ('aria-label="Outdoor spaces"', 'aria-label="Dış mekânlar"'),
 ('data-garden="0" aria-pressed="true">The pool</button>', 'data-garden="0" aria-pressed="true">Havuz</button>'),
 ('data-garden="1" aria-pressed="false">The terrace</button>', 'data-garden="1" aria-pressed="false">Teras</button>'),
 ('data-garden="2" aria-pressed="false">The garden</button>', 'data-garden="2" aria-pressed="false">Bahçe</button>'),
 ('<span class="eyebrow" id="garden-number">01 / Your own water</span><h3 id="garden-title">A pool, all to yourself.</h3><p id="garden-text">The private pool sits at the same level as the lower living floor. Open the doors, cross the terrace and the day moves outside.</p>',
  '<span class="eyebrow" id="garden-number">01 / Kendi suyunuz</span><h3 id="garden-title">Yalnızca size ait bir havuz.</h3><p id="garden-text">Özel havuz, alt yaşam katıyla aynı kottadır. Kapıları açın, terası geçin; gün dışarı taşınsın.</p>'),
 ('<span class="garden-foot eyebrow">900 m² garden · Private pool · Covered terrace</span>', '<span class="garden-foot eyebrow">900 m² bahçe · Özel havuz · Üstü kapalı teras</span>'),
 ('<span class="eyebrow">03 / Inside the home</span><span class="eyebrow">Warmth. Character. Room to breathe.</span>', '<span class="eyebrow">03 / Evin içi</span><span class="eyebrow">Sıcaklık. Karakter. Nefes alacak yer.</span>'),
 ('Come together.<br><em>Feel at home.</em>', 'Bir araya gelin.<br><em>Evinizde hissedin.</em>'),
 ('<p class="copy" data-reveal="fade">This is a home with its own character: timber floors, generous windows, wrought-iron stair rails and rooms that connect through a central hall. The social spaces and private rooms have their own place in the house.</p>',
  '<p class="copy" data-reveal="fade">Bu, kendi karakteri olan bir ev: ahşap zeminler, geniş pencereler, ferforje merdiven korkulukları ve merkezi bir holle birbirine bağlanan odalar. Sosyal alanlar ve özel odalar evde kendi yerlerine sahip.</p>'),
 ('data-caption="The main living and dining room" aria-label="Enlarge living room photograph"', 'data-caption="Ana salon ve yemek odası" aria-label="Salon fotoğrafını büyüt"'),
 ('alt="Main living and dining room"', 'alt="Ana salon ve yemek odası"'),
 ('<span>View photograph ↗</span>', '<span>Fotoğrafı görün ↗</span>'),
 ('<span class="eyebrow">The entrance level</span><h3 data-reveal="lines">A room for<br><em>everyone.</em></h3><p data-reveal="fade">The main living and dining room extends across approximately 53 m². Large windows bring in daylight, while the balcony looks towards the pool and garden below.</p><p data-reveal="fade">At street level, the entrance hall connects this social floor to the kitchen, staircase, lift and garage.</p><button type="button" class="text-link" data-floor-link="1">Explore the entrance level ↗</button>',
  '<span class="eyebrow">Giriş katı</span><h3 data-reveal="lines">Herkese<br><em>yer olan bir oda.</em></h3><p data-reveal="fade">Ana salon ve yemek odası yaklaşık 53 m² boyunca uzanır. Geniş pencereler gün ışığını içeri alır; balkon aşağıdaki havuza ve bahçeye bakar.</p><p data-reveal="fade">Sokak kotunda antre, bu sosyal katı mutfağa, merdivene, asansöre ve garaja bağlar.</p><button type="button" class="text-link" data-floor-link="1">Giriş katını keşfedin ↗</button>'),
 ('alt="Timber flooring and dining area detail"', 'alt="Ahşap zemin ve yemek alanı detayı"'), ('<figcaption>Daylight, timber &amp; everyday life</figcaption>', '<figcaption>Gün ışığı, ahşap ve gündelik hayat</figcaption>'),
 ('<span class="eyebrow">The first floor</span><h3 data-reveal="lines">A little more<br><em>privacy.</em></h3><p data-reveal="fade">The principal suite brings together a bedroom, a separate dressing room and an en-suite bathroom. A balcony adds a quiet connection to the outdoors.</p><p data-reveal="fade">Two further bedrooms, a family bathroom and a sitting area share this level, keeping the family’s private rooms together.</p><button type="button" class="text-link" data-floor-link="2">Discover the bedroom floor ↗</button>',
  '<span class="eyebrow">Birinci kat</span><h3 data-reveal="lines">Biraz daha<br><em>mahremiyet.</em></h3><p data-reveal="fade">Ebeveyn süiti bir yatak odasını, ayrı bir giyinme odasını ve ebeveyn banyosunu bir araya getirir. Balkon dışarıyla sessiz bir bağ kurar.</p><p data-reveal="fade">İki yatak odası daha, ortak banyo ve bir oturma alanı bu katı paylaşır; ailenin özel odaları bir arada kalır.</p><button type="button" class="text-link" data-floor-link="2">Yatak odası katını keşfedin ↗</button>'),
 ('data-caption="The principal bedroom" aria-label="Enlarge principal bedroom photograph"', 'data-caption="Ebeveyn yatak odası" aria-label="Ebeveyn yatak odası fotoğrafını büyüt"'),
 ('alt="The principal bedroom with timber flooring"', 'alt="Ahşap zeminli ebeveyn yatak odası"'),
 ('alt="Separate dressing room in the principal suite"', 'alt="Ebeveyn süitindeki ayrı giyinme odası"'), ('<figcaption>A suite with a dressing room of its own</figcaption>', '<figcaption>Kendi giyinme odası olan bir süit</figcaption>'),
 ('aria-label="Three kitchens, three daily rhythms"', 'aria-label="Üç mutfak, üç günlük ritim"'),
 ('<span class="eyebrow">Space for different routines</span>', '<span class="eyebrow">Farklı rutinlere yer</span>'),
 ('<h2 data-reveal="lines">Gather.<br><em>And make it yours.</em></h2>', '<h2 data-reveal="lines">Toplanın.<br><em>Ve kendinizin kılın.</em></h2>'),
 ('<p data-reveal="fade">A full kitchen on the social floor, another beside the garden and a kitchenette under the roof.</p>', '<p data-reveal="fade">Sosyal katta tam bir mutfak, bahçenin yanında bir diğeri ve çatının altında bir mini mutfak.</p>'),
 ('aria-label="Three kitchens, scroll sideways on a phone"', 'aria-label="Üç mutfak, telefonda yana kaydırın"'),
 ('alt="The entrance-level kitchen"', 'alt="Giriş katı mutfağı"'), ('<figcaption>01 / The main kitchen</figcaption>', '<figcaption>01 / Ana mutfak</figcaption>'),
 ('alt="The garden-level kitchen"', 'alt="Bahçe katı mutfağı"'), ('<figcaption>02 / Garden-level independence</figcaption>', '<figcaption>02 / Bahçe katında bağımsızlık</figcaption>'),
 ('alt="The attic kitchenette"', 'alt="Çatı katı mini mutfağı"'), ('<figcaption>03 / A quieter upper level</figcaption>', '<figcaption>03 / Daha sakin bir üst kat</figcaption>'),
 ('<span class="eyebrow">04 / A home in four chapters</span><span class="eyebrow">Scroll through the levels</span>', '<span class="eyebrow">04 / Dört bölümlük bir ev</span><span class="eyebrow">Katlar arasında kaydırın</span>'),
 ('<h2>One home.<br><em>Four chapters.</em></h2>', '<h2>Bir ev.<br><em>Dört bölüm.</em></h2>'),
 ('aria-label="Villa levels"', 'aria-label="Villa katları"'),
 ('data-floor="0"><span>1</span>Garden level</button>', 'data-floor="0"><span>1</span>Bahçe katı</button>'),
 ('data-floor="1"><span>2</span>Entrance level</button>', 'data-floor="1"><span>2</span>Giriş katı</button>'),
 ('data-floor="2"><span>3</span>First floor</button>', 'data-floor="2"><span>3</span>Birinci kat</button>'),
 ('data-floor="3"><span>4</span>Attic level</button>', 'data-floor="3"><span>4</span>Çatı katı</button>'),
 ('<span class="eyebrow" id="floor-kicker">1 / The garden floor</span><h3 id="floor-title">Open the day outside.</h3><p id="floor-copy">A living room of approximately 54 m², a separate kitchen and direct access to the garden and pool. An annexe with its own entrance adds space for guests, work or a separate daily routine.</p><ul id="floor-features"><li>Living room &amp; kitchen</li><li>Garden &amp; pool access</li><li>Guest WC &amp; separate annexe</li></ul><a class="text-link" id="floor-plan-link" href="#atlas">See this floor’s plan ↗</a>',
  '<span class="eyebrow" id="floor-kicker">1 / Bahçe katı</span><h3 id="floor-title">Günü dışarıda açın.</h3><p id="floor-copy">Yaklaşık 54 m² bir salon, ayrı bir mutfak ve bahçeye ve havuza doğrudan erişim. Kendi girişi olan ek bina misafirler, çalışma ya da ayrı bir günlük rutin için alan katar.</p><ul id="floor-features"><li>Salon &amp; mutfak</li><li>Bahçe &amp; havuz erişimi</li><li>Misafir WC &amp; ayrı ek bina</li></ul><a class="text-link" id="floor-plan-link" href="#atlas">Bu katın planını görün ↗</a>'),
 ('alt="The villa model cut at the garden level"', 'alt="Villa modeli bahçe katından kesilmiş"'),
 ('<div class="floors-caption"><span id="floor-level">Garden level</span><span>Four levels. One home.</span></div>', '<div class="floors-caption"><span id="floor-level">Bahçe katı</span><span>Dört kat. Bir ev.</span></div>'),
 ('<span class="eyebrow">05 / The house, revealed</span><span class="eyebrow">Plans · Photographs · Dimensions</span>', '<span class="eyebrow">05 / Ev, açılıyor</span><span class="eyebrow">Planlar · Fotoğraflar · Ölçüler</span>'),
 ('Inside <em>every level.</em></h2><p data-reveal="fade">Follow a photograph back to the space it depicts. Choose a level, then a camera point, to see the room from that exact position.</p>',
  'Her katın <em>içinde.</em></h2><p data-reveal="fade">Bir fotoğrafı gösterdiği mekâna kadar takip edin. Bir kat, sonra bir kamera noktası seçin; odayı tam o konumdan görün.</p>'),
 ('aria-label="Floor plans"', 'aria-label="Kat planları"'),
 ('data-atlas-floor="0"><span>1</span>Garden</button>', 'data-atlas-floor="0"><span>1</span>Bahçe</button>'),
 ('data-atlas-floor="1"><span>2</span>Entrance</button>', 'data-atlas-floor="1"><span>2</span>Giriş</button>'),
 ('data-atlas-floor="2"><span>3</span>First floor</button>', 'data-atlas-floor="2"><span>3</span>Birinci kat</button>'),
 ('data-atlas-floor="3"><span>4</span>Attic</button>', 'data-atlas-floor="3"><span>4</span>Çatı</button>'),
 ('class="measure-toggle">Dimensions <span aria-hidden="true">＋</span></button>', 'class="measure-toggle">Ölçüler <span aria-hidden="true">＋</span></button>'),
 ('<div class="atlas-plan-title"><span id="atlas-level">Garden level</span><span>Choose a camera point</span></div>', '<div class="atlas-plan-title"><span id="atlas-level">Bahçe katı</span><span>Bir kamera noktası seçin</span></div>'),
 ('alt="Furnished model plan of the garden level"', 'alt="Bahçe katının mobilyalı model planı"'),
 ('aria-label="Registered camera positions and dimensions"', 'aria-label="Kayıtlı kamera konumları ve ölçüler"'),
 ('<div class="atlas-plan-foot"><span><i></i> Camera position &amp; view</span><span>0 ━━━━━ 5 m</span></div>', '<div class="atlas-plan-foot"><span><i></i> Kamera konumu &amp; bakış</span><span>0 ━━━━━ 5 m</span></div>'),
 ('aria-label="Enlarge selected floor photograph"', 'aria-label="Seçili kat fotoğrafını büyüt"'),
 ('alt="Garden-level living room"', 'alt="Bahçe katı salonu"'),
 ('<span class="eyebrow" id="atlas-photo-number">Camera 3 · Garden level</span><h3 id="atlas-photo-title">Living room</h3><p id="atlas-photo-description">Garden level</p>', '<span class="eyebrow" id="atlas-photo-number">Kamera 3 · Bahçe katı</span><h3 id="atlas-photo-title">Salon</h3><p id="atlas-photo-description">Bahçe katı</p>'),
 ('aria-label="Photographs on this floor"', 'aria-label="Bu kattaki fotoğraflar"'),
 ('<span class="eyebrow">A sense of scale</span><h3 id="atlas-schedule-heading">The garden floor</h3>', '<span class="eyebrow">Ölçek duygusu</span><h3 id="atlas-schedule-heading">Bahçe katı</h3>'),
 ('<p class="note">Camera positions follow the supplied photo-location drawing. Dimensions follow the supplied DXF; room areas follow the owner’s schedule where available. Areas are approximate, and are not a survey of net usable space.</p>',
  '<p class="note">Kamera konumları, iletilen fotoğraf-konum çizimini izler. Ölçüler iletilen DXF dosyasından; oda alanları mevcut olduğunda mal sahibinin listesinden alınmıştır. Alanlar yaklaşıktır; net kullanılabilir alan ölçümü değildir.</p>'),
 ('<span class="eyebrow">The details that make a home</span><span class="eyebrow">Space, access &amp; practical comfort</span>', '<span class="eyebrow">Bir evi ev yapan ayrıntılar</span><span class="eyebrow">Alan, erişim &amp; pratik konfor</span>'),
 ('A home that<br><em>works for life.</em>', 'Hayat için<br><em>çalışan bir ev.</em>'),
 ('<span>01</span><h3>A lift &amp; a staircase</h3><p>A lift serves the garden, entrance and first floors. The attic is reached by the staircase, whose iron balustrades and timber handrails carry the character of the home between levels.</p>',
  '<span>01</span><h3>Asansör &amp; merdiven</h3><p>Asansör bahçe, giriş ve birinci katlara hizmet eder. Çatı katına, ferforje korkulukları ve ahşap küpeşteleriyle evin karakterini katlar arasında taşıyan merdivenle ulaşılır.</p>'),
 ('<span>02</span><h3>Space for arriving</h3><p>An internally connected garage and open parking provide room for three vehicles in total. The covered entrance creates a sheltered transition from the street into the home.</p>',
  '<span>02</span><h3>Varış için alan</h3><p>İçeriden bağlantılı garaj ve açık otopark toplam üç araca yer sağlar. Üstü kapalı giriş, sokaktan eve korunaklı bir geçiş oluşturur.</p>'),
 ('<span>03</span><h3>Independent possibilities</h3><p>The annexe has its own entrance. Together with a kitchen on the lower floor and a kitchenette in the attic, the layout accommodates guests, family members or working from home.</p>',
  '<span>03</span><h3>Bağımsız olasılıklar</h3><p>Ek binanın kendi girişi vardır. Alt kattaki mutfak ve çatı katındaki mini mutfakla birlikte yerleşim misafirleri, aile bireylerini ya da evden çalışmayı ağırlar.</p>'),
 ('<span>04</span><h3>Everyday essentials</h3><p>Gas combi heating, a 6-tonne water tank, three bathrooms, two guest WCs and two balconies complement the living spaces and garden.</p>',
  '<span>04</span><h3>Gündelik temeller</h3><p>Doğalgaz kombi, 6 tonluk su deposu, üç banyo, iki misafir WC’si ve iki balkon yaşam alanlarını ve bahçeyi tamamlar.</p>'),
 ('alt="Villa staircase with iron balustrades and timber handrail"', 'alt="Ferforje korkuluklu ve ahşap küpeşteli villa merdiveni"'),
 ('<figcaption>Connected by more than a staircase.</figcaption>', '<figcaption>Bir merdivenden fazlasıyla bağlı.</figcaption>'),
 ('<span class="eyebrow">06 / The neighbourhood</span><span class="eyebrow">Angora Evleri · Ankara</span>', '<span class="eyebrow">06 / Mahalle</span><span class="eyebrow">Angora Evleri · Ankara</span>'),
 ('alt="Aerial view of the villa among Angora Evleri\'s gardens and detached houses"', 'alt="Angora Evleri’nin bahçeleri ve müstakil evleri arasında villanın havadan görünümü"'),
 ('<span class="eyebrow">Mutlukent, Çankaya</span><h2 data-reveal="lines">A quieter side of <em>the city.</em></h2><p data-reveal="fade">Angora Evleri is an established villa neighbourhood in Ankara’s Mutlukent district. Detached homes, mature gardens and residential streets give the setting its own scale and rhythm.</p><p data-reveal="fade">The villa sits on Hatırlı Sokak, with the Eskişehir road and Bilkent connections placing it within reach of the wider city.</p>',
  '<span class="eyebrow">Mutlukent, Çankaya</span><h2 data-reveal="lines">Şehrin daha sakin <em>bir yüzü.</em></h2><p data-reveal="fade">Angora Evleri, Ankara Mutlukent’te yerleşik bir villa mahallesidir. Müstakil evler, olgun bahçeler ve konut sokakları çevreye kendi ölçeğini ve ritmini verir.</p><p data-reveal="fade">Villa Hatırlı Sokak üzerindedir; Eskişehir yolu ve Bilkent bağlantıları şehrin geneline kolay erişim sağlar.</p>'),
 ('<button type="button" class="text-link" data-tour="neighborhood">Explore the neighbourhood in 3D ↗</button>', '<button type="button" class="text-link" data-tour="neighborhood">Mahalleyi 3B’de keşfedin ↗</button>'),
 ('alt="North-up neighbourhood map: Angora 21 is marked, the dashed Angora Evleri boundary is identified, and coloured dots show six amenity categories"', 'alt="Kuzeyi yukarıda mahalle haritası: Angora 21 işaretli, kesikli Angora Evleri sınırı gösterili, renkli noktalar altı donatı kategorisini gösteriyor"'),
 ('<span class="eyebrow">07 / Life in Angora</span>', '<span class="eyebrow">07 / Angora’da yaşam</span>'),
 ('<h2 id="life-heading" data-reveal="lines">A place.<br>A season.<br><em>A way of life.</em></h2>', '<h2 id="life-heading" data-reveal="lines">Bir yer.<br>Bir mevsim.<br><em>Bir yaşam biçimi.</em></h2>'),
 ('<p data-reveal="fade">A quiet morning at home. A class in the neighbourhood. An evening with the orchestra. A considered guide to Angora and the wider city.</p>', '<p data-reveal="fade">Evde sakin bir sabah. Mahallede bir ders. Orkestrayla bir akşam. Angora ve şehre özenli bir rehber.</p>'),
 ('aria-label="Map layers"', 'aria-label="Harita katmanları"'),
 ('<li><i style="--dot:#8298b4"></i>Education</li><li><i style="--dot:#c08e9a"></i>Health</li><li><i style="--dot:#c8a976"></i>Food &amp; drink</li><li><i style="--dot:#b7a06c"></i>Shopping</li><li><i style="--dot:#8fae8b"></i>Parks &amp; sport</li><li><i style="--dot:#a2a8a2"></i>Services</li>',
  '<li><i style="--dot:#8298b4"></i>Eğitim</li><li><i style="--dot:#c08e9a"></i>Sağlık</li><li><i style="--dot:#c8a976"></i>Yeme &amp; içme</li><li><i style="--dot:#b7a06c"></i>Alışveriş</li><li><i style="--dot:#8fae8b"></i>Park &amp; spor</li><li><i style="--dot:#a2a8a2"></i>Hizmetler</li>'),
 ('<span class="eyebrow">The Angora journal</span><span class="eyebrow">A local perspective · Autumn edition</span>', '<span class="eyebrow">Angora günlüğü</span><span class="eyebrow">Yerel bir bakış · Sonbahar sayısı</span>'),
 ('<h3 data-reveal="lines">Belong to<br><em>the everyday.</em></h3><p data-reveal="fade">In Mutlukent, Angora Evleri has a residential rhythm of its own. Its residents’ association describes a community of neighbourly contact, green spaces, sports areas and children’s play spaces.</p>',
  '<h3 data-reveal="lines">Gündelik olana<br><em>ait olun.</em></h3><p data-reveal="fade">Mutlukent’te Angora Evleri’nin kendine özgü bir konut ritmi var. Site yönetimi komşuluk ilişkileri, yeşil alanlar, spor sahaları ve çocuk oyun alanlarıyla bir topluluk tarif ediyor.</p>'),
 ('alt="Angora’s communal green spaces and homes in autumn"', 'alt="Angora’nın ortak yeşil alanları ve evleri sonbaharda"'),
 ('<figcaption>Angora residents’ association · Autumn interpretation</figcaption>', '<figcaption>Angora site yönetimi · Sonbahar yorumu</figcaption>'),
 ('<span class="eyebrow">01 / A greener everyday</span><h4 data-reveal="lines">Begin with<br><em>a slower morning.</em></h4><p data-reveal="fade">Angora’s residents’ association describes green areas, neighbourly contact and shared outdoor spaces. The neighbourhood’s mature landscape sets the tone for a quieter daily rhythm.</p><a href="https://www.angorakoop18.com/" target="_blank" rel="noopener" class="text-link">Within the neighbourhood ↗</a>',
  '<span class="eyebrow">01 / Daha yeşil bir gündelik</span><h4 data-reveal="lines">Daha yavaş<br><em>bir sabahla başlayın.</em></h4><p data-reveal="fade">Angora site yönetimi yeşil alanları, komşuluk ilişkilerini ve ortak dış mekânları anlatıyor. Mahallenin olgun peyzajı daha sakin bir günlük ritmin tonunu belirliyor.</p><a href="https://www.angorakoop18.com/" target="_blank" rel="noopener" class="text-link">Mahallenin içinde ↗</a>'),
 ('alt="Angora’s recreation grounds in autumn"', 'alt="Angora’nın spor ve rekreasyon alanları sonbaharda"'),
 ('<span class="eyebrow">02 / Room to come together</span><h4 data-reveal="lines">A shared<br><em>sense of place.</em></h4><p data-reveal="fade">Sports and social spaces are part of the community’s own account of life here. Beyond the garden gate, everyday routines have room to become familiar rituals.</p><a href="https://www.angorakoop18.com/" target="_blank" rel="noopener" class="text-link">Community &amp; recreation ↗</a>',
  '<span class="eyebrow">02 / Bir araya gelmeye yer</span><h4 data-reveal="lines">Paylaşılan<br><em>bir yer duygusu.</em></h4><p data-reveal="fade">Spor ve sosyal alanlar, topluluğun buradaki hayatı kendi anlatımının parçası. Bahçe kapısının ötesinde gündelik rutinler tanıdık ritüellere dönüşecek yer buluyor.</p><a href="https://www.angorakoop18.com/" target="_blank" rel="noopener" class="text-link">Topluluk &amp; rekreasyon ↗</a>'),
 ('<span class="eyebrow">A day further into Ankara</span><p data-reveal="fade">Make an evening of Bilkent Symphony Orchestra’s season concerts. For a day with contemporary art, explore CerModern in Sıhhiye, with its exhibitions, café and library.</p><div><a href="https://bso.bilkent.edu.tr/en/" target="_blank" rel="noopener" class="text-link">The Bilkent concert season ↗</a><a href="https://www.cermodern.org/ziyaret" target="_blank" rel="noopener" class="text-link">Plan a CerModern visit ↗</a></div>',
  '<span class="eyebrow">Ankara’nın içine doğru bir gün</span><p data-reveal="fade">Bilkent Senfoni Orkestrası’nın sezon konserlerinden bir akşam çıkarın. Çağdaş sanatla bir gün için Sıhhiye’deki CerModern’i; sergilerini, kafesini ve kütüphanesini keşfedin.</p><div><a href="https://bso.bilkent.edu.tr/" target="_blank" rel="noopener" class="text-link">Bilkent konser sezonu ↗</a><a href="https://www.cermodern.org/ziyaret" target="_blank" rel="noopener" class="text-link">CerModern ziyareti planlayın ↗</a></div>'),
 ('<p class="note">An editorial selection from official sources, checked 3 October 2026. Community photographs are AI-restored seasonal interpretations; the buildings and locations follow their source images.</p>', '<p class="note">Resmî kaynaklardan editoryal bir seçki, 3 Ekim 2026’da kontrol edildi. Topluluk fotoğrafları yapay zekâyla restore edilmiş mevsimsel yorumlardır; binalar ve konumlar kaynak görüntülerini izler.</p>'),
 ('<span class="eyebrow">08 / The residence, as it is</span>', '<span class="eyebrow">08 / Villa, olduğu gibi</span>'),
 ('aria-label="Previous photograph"', 'aria-label="Önceki fotoğraf"'), ('aria-label="Next photograph"', 'aria-label="Sonraki fotoğraf"'),
 ('<h2 class="display">Take a closer <em>look.</em></h2>', '<h2 class="display">Daha yakından <em>bakın.</em></h2>'),
 ('aria-label="Filter photographs"', 'aria-label="Fotoğrafları süz"'),
 ('data-gallery-filter="all" aria-pressed="true">Selected views</button>', 'data-gallery-filter="all" aria-pressed="true">Seçilmiş kareler</button>'),
 ('data-gallery-filter="outdoor" aria-pressed="false">Garden &amp; exterior</button>', 'data-gallery-filter="outdoor" aria-pressed="false">Bahçe &amp; dış mekân</button>'),
 ('data-gallery-filter="0" aria-pressed="false">Garden level</button>', 'data-gallery-filter="0" aria-pressed="false">Bahçe katı</button>'),
 ('data-gallery-filter="1" aria-pressed="false">Entrance level</button>', 'data-gallery-filter="1" aria-pressed="false">Giriş katı</button>'),
 ('data-gallery-filter="2" aria-pressed="false">First floor</button>', 'data-gallery-filter="2" aria-pressed="false">Birinci kat</button>'),
 ('data-gallery-filter="3" aria-pressed="false">Attic</button>', 'data-gallery-filter="3" aria-pressed="false">Çatı katı</button>'),
 ('aria-label="Photograph gallery; use the arrow keys to browse"', 'aria-label="Fotoğraf galerisi; ok tuşlarıyla gezin"'),
 ('alt="Angora 21: the garden-facing house, terrace and private pool"', 'alt="Angora 21: bahçeye bakan ev, teras ve özel havuz"'),
 ('<span class="eyebrow">09 / The opportunity</span>', '<span class="eyebrow">09 / Fırsat</span>'),
 ('<h2 data-reveal="lines">A place to<br><em>call your own.</em></h2>', '<h2 data-reveal="lines">Sizin diyeceğiniz<br><em>bir yer.</em></h2>'),
 ('<p data-reveal="fade">A detached villa on Hatırlı Sokak with approximately 500 m² gross interior space, 400 m² net living space and a 900 m² private garden. Five bedrooms, four living spaces, three kitchens, a private pool, a lift, an independently accessed annexe and parking for three cars.</p>',
  '<p data-reveal="fade">Hatırlı Sokak’ta yaklaşık 500 m² brüt kapalı alan, 400 m² net yaşam alanı ve 900 m² özel bahçesi olan müstakil bir villa. Beş yatak odası, dört yaşam alanı, üç mutfak, özel havuz, asansör, bağımsız girişli ek bina ve üç araçlık otopark.</p>'),
 ('<span class="eyebrow">Asking price</span>', '<span class="eyebrow">İstenen fiyat</span>'),
 ('<small>Listing checked 4 October 2026 · RE/MAX Türkiye</small>', '<small>İlan 4 Ekim 2026’da kontrol edildi · RE/MAX Türkiye</small>'),
 ('<li>Detached villa</li><li>Four floors</li><li>Vacant · Available now</li>', '<li>Müstakil villa</li><li>Dört kat</li><li>Boş · Hemen teslim</li>'),
 ('<label><span>Your name</span>', '<label><span>Adınız</span>'), ('<label><span>Phone or e-mail</span>', '<label><span>Telefon veya e-posta</span>'),
 ('<label class="wide"><span>When would you like to visit?</span><input name="when" type="text" placeholder="A day and time that suits you"></label>', '<label class="wide"><span>Ne zaman ziyaret etmek istersiniz?</span><input name="when" type="text" placeholder="Size uygun bir gün ve saat"></label>'),
 ('<button type="submit" class="button">Arrange a viewing ↗</button>', '<button type="submit" class="button">Randevu alın ↗</button>'),
 ('<a class="text-link" href="tel:+905333048359">Or call +90 533 304 83 59</a>', '<a class="text-link" href="tel:+905333048359">Ya da arayın: +90 533 304 83 59</a>'),
 ('RE/MAX · P56131836 · Listing &amp; asking price ↗', 'RE/MAX · P56131836 · İlan &amp; istenen fiyat ↗'),
 ('<span class="eyebrow">Your next chapter</span>', '<span class="eyebrow">Sıradaki bölümünüz</span>'),
 ('<h2 id="footer-heading">Make it<br><em>your own.</em></h2>', '<h2 id="footer-heading">Kendinizin<br><em>kılın.</em></h2>'),
 ('<a href="#contact">Arrange a viewing <span>↗</span></a>', '<a href="#contact">Randevu alın <span>↗</span></a>'),
 ('<a href="./index.html?lang=en&amp;view=building" target="_blank" rel="noopener">Explore the 3D residence <span>↗</span></a>', '<a href="./index.html?lang=tr&amp;view=building" target="_blank" rel="noopener">3B villayı keşfedin <span>↗</span></a>'),
 ('<a href="https://remax.com.tr/tr/portfoy/P56131836" target="_blank" rel="noopener">View the listing <span>↗</span></a>', '<a href="https://remax.com.tr/tr/portfoy/P56131836" target="_blank" rel="noopener">İlanı görün <span>↗</span></a>'),
 ('<p>A private world, within the city.<br>Angora Evleri · Ankara</p>', '<p>Şehrin içinde, size ait bir dünya.<br>Angora Evleri · Ankara</p>'),
 ('<a href="#home">Back to top ↑</a>', '<a href="#home">Başa dön ↑</a>'),
 ('Angora 21 · Villa imagery supplied by the owner. Community images are seasonal editorial adaptations of official photographs. Approximate areas and facilities follow the supplied listing; the digital model is an exploration of the layout. The opening camera films are illustrative.',
  'Angora 21 · Villa görselleri mal sahibi tarafından sağlanmıştır. Topluluk görselleri resmî fotoğrafların mevsimsel editoryal uyarlamalarıdır. Yaklaşık alanlar ve donanım ilan metnini izler; dijital model yerleşimin bir keşfidir. Açılış kamera filmleri temsilîdir.'),
 ('<span class="brand-credit">Developed by MERGVS · Luxembourg</span>', '<span class="brand-credit">MERGVS · Lüksemburg tarafından geliştirildi</span>'),
 ('aria-label="Close photograph"', 'aria-label="Fotoğrafı kapat"'), ('>Close ×</button>', '>Kapat ×</button>'),
]

STRINGS = {
 'lang': 'tr',
 'levels': ['Bahçe katı', 'Giriş katı', 'Birinci kat', 'Çatı katı'],
 'camera': 'Kamera ', 'cameraPoint': 'Kamera noktası ', 'dimensions': 'Ölçüler', 'enlarge': 'Büyüt', 'planAlt': 'Mobilyalı model planı: ',
 'rooms': {'Living room': 'Salon', 'Kitchen': 'Mutfak', 'Hall & stairs': 'Hol ve merdiven', 'Hall': 'Hol', 'Annexe': 'Ek bina', 'Dining area': 'Yemek alanı', 'Entry hall': 'Antre', 'Entrance': 'Giriş', 'Guest WC': 'Misafir WC', 'WC': 'WC', 'Garage': 'Garaj', 'Utility': 'Kiler', 'Principal bedroom': 'Ebeveyn yatak odası', 'Dressing room': 'Giyinme odası', 'En-suite': 'Ebeveyn banyosu', 'Sitting area': 'Oturma alanı', 'Landing': 'Kat holü', 'Bedroom': 'Yatak odası', 'Bathroom': 'Banyo', 'Landing & kitchenette': 'Kat holü ve mini mutfak', 'Suite balcony': 'Süit balkonu', 'Balcony': 'Balkon'},
 'exteriors': [['angora_28.jpeg', 'Sokak cephesi'], ['angora_24.jpg', 'Özel bahçe ve havuz'], ['angora_26.jpg', 'Bahçeye bakan cephe'], ['angora_27.jpg', 'Üstü kapalı teras ve su']],
 'gardens': [
  ['01 / Kendi suyunuz', 'Yalnızca size ait bir havuz.', 'Özel havuz, alt yaşam katıyla aynı kottadır. Kapıları açın, terası geçin; gün dışarı taşınsın.'],
  ['02 / Gölgede bir yer', 'Biraz daha kalın.', 'Üstü kapalı teras acelesiz öğle yemeklerine, sakin sabahlara ve uzun akşamlara yer açar. Bahçe katı odalarını havuzla ve açık yemek alanıyla birleştirir.'],
  ['03 / Nefes alacak yer', 'Kendi ritmi olan bir bahçe.', 'Yaklaşık 900 m² özel bahçe villayı çevreler. Olgun bitkiler, çim ve yollar oturmak, oynamak ve dışarıda vakit geçirmek için farklı yerler yaratır.']],
 'chapters': [
  {'level': 'Bahçe katı', 'kicker': '1 / Bahçe katı', 'title': 'Günü dışarıda açın.', 'copy': 'Yaklaşık 54 m² bir salon, ayrı bir mutfak ve bahçeye ve havuza doğrudan erişim. Kendi girişi olan ek bina misafirler, çalışma ya da ayrı bir günlük rutin için alan katar.', 'features': ['Salon & mutfak', 'Bahçe & havuz erişimi', 'Misafir WC & ayrı ek bina']},
  {'level': 'Giriş katı', 'kicker': '2 / Giriş katı', 'title': 'Evin kalbi.', 'copy': 'Sokaktan ana sosyal kata varın. Yaklaşık 53 m² salon ve yemek odası geniş kapalı mutfağa, kilere ve içeriden erişilen garaja bağlanır.', 'features': ['Ana salon & yemek odası', 'Mutfak, kiler & misafir WC', 'Sokak girişi, garaj & balkon']},
  {'level': 'Birinci kat', 'kicker': '3 / Yatak odası katı', 'title': 'Mahremiyet için bir yer.', 'copy': 'Ebeveyn süitinin kendi giyinme odası ve banyosu vardır. İki yatak odası daha, ortak banyo ve bir oturma alanı özel odaları tek katta toplar.', 'features': ['Ebeveyn süiti & giyinme odası', 'İki yatak odası & ortak banyo', 'Oturma alanı, balkon & asansör']},
  {'level': 'Çatı katı', 'kicker': '4 / Çatı katı', 'title': 'Başka bir ritme yer.', 'copy': 'Eğimli çatının altında bir oturma odası, iki yatak odası, mini mutfak ve banyo ek bir yaşam düzeni kurar. Misafirler, büyümüş çocuklar ya da daha sakin bir çalışma günü için; merdivenle ulaşılır.', 'features': ['Oturma odası & iki yatak odası', 'Mini mutfak & banyo', 'Merdivenle erişim; asansör alt katta durur']}],
}

out = html
missing = []
for en, tr in T:
    if en not in out:
        missing.append(en[:80]); continue
    out = out.replace(en, tr)
if missing:
    print('MISSING:', *missing, sep='\n  '); sys.exit(1)

# language links + hreflang
out = out.replace('<link rel="icon" href="./favicon.svg">', '<link rel="icon" href="./favicon.svg">\n  <link rel="alternate" hreflang="en" href="./web2.html">\n  <link rel="alternate" hreflang="tr" href="./web2-tr.html">')
out = out.replace('<button class="menu-toggle"', '<a class="lang-switch" href="./web2.html" lang="en" hreflang="en" aria-label="English">EN</a>\n    <button class="menu-toggle"')
out = out.replace('<script src="./web2.js" defer></script>', '<script>window.ANGORA_STRINGS=' + json.dumps(STRINGS, ensure_ascii=False) + ';</script>\n  <script src="./web2.js" defer></script>')
(root / 'web2-tr.html').write_text(out, encoding='utf-8')

# the English page gets the mirror link and hreflang too
en = html
if 'hreflang="tr"' not in en:
    en = en.replace('<link rel="icon" href="./favicon.svg">', '<link rel="icon" href="./favicon.svg">\n  <link rel="alternate" hreflang="en" href="./web2.html">\n  <link rel="alternate" hreflang="tr" href="./web2-tr.html">')
    en = en.replace('<button class="menu-toggle"', '<a class="lang-switch" href="./web2-tr.html" lang="tr" hreflang="tr" aria-label="Türkçe">TR</a>\n    <button class="menu-toggle"')
    (root / 'web2.html').write_text(en, encoding='utf-8')
print('built web2-tr.html', len(out), 'chars;', len(T), 'strings')
